/** @file     Rte_DataHandleType.h
  * 
  * @brief    RTE DataElement type definitions
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.3  (R4.0 backend version: v7.8.6 (Build 46625))
  * 
  * @note     Suppressed errors detected.
  *           E51-7061, E51-7061, E51-7061, E51-7061, E51-7061
  *           E51-7061, E51-7061, E51-7061, E51-7061, E51-7061
  *           E51-7061, E51-7061
  */

#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

#include "Rte_Type.h"
#include "Rte_Cfg.h"

typedef struct {
   A33 value;
} Rte_DE_A33;

typedef struct {
   ADataRawSafe1 value;
} Rte_DE_ADataRawSafe1;

typedef struct {
   ALatFromOffsCmp0 value;
} Rte_DE_ALatFromOffsCmp0;

typedef struct {
   ALgtFromOffsCmpRec value;
} Rte_DE_ALgtFromOffsCmpRec;

typedef struct {
   ALgtHardMaxReq0 value;
} Rte_DE_ALgtHardMaxReq0;

typedef struct {
   ALgtMinReq0 value;
} Rte_DE_ALgtMinReq0;

typedef struct {
   ALgtReqAttrbArbd0 value;
} Rte_DE_ALgtReqAttrbArbd0;

typedef struct {
   ALgtSoftMaxReq0 value;
} Rte_DE_ALgtSoftMaxReq0;

typedef struct {
   ALgtStdFromWhlSpdSafe1 value;
} Rte_DE_ALgtStdFromWhlSpdSafe1;

typedef struct {
   AbsCtrlActvForWhlRec1 value;
} Rte_DE_AbsCtrlActvForWhlRec1;

typedef struct {
   AccSts1 value;
} Rte_DE_AccSts1;

typedef struct {
   AccrPedlPsdSafe1 value;
} Rte_DE_AccrPedlPsdSafe1;

typedef struct {
   AdjSpdLimnSts2 value;
} Rte_DE_AdjSpdLimnSts2;

typedef struct {
   AgDataRawSafe1 value;
} Rte_DE_AgDataRawSafe1;

typedef struct {
   AirPInAirSprg0 value;
} Rte_DE_AirPInAirSprg0;

typedef struct {
   AmbTIndcdWithUnit0 value;
} Rte_DE_AmbTIndcdWithUnit0;

typedef struct {
   AmbTRaw0 value;
} Rte_DE_AmbTRaw0;

typedef struct {
   AsyALgtReqRngForCmft0 value;
} Rte_DE_AsyALgtReqRngForCmft0;

typedef struct {
   AsyALgtRespAndLim1 value;
} Rte_DE_AsyALgtRespAndLim1;

typedef struct {
   AsyBrkEnaAckd0 value;
} Rte_DE_AsyBrkEnaAckd0;

typedef struct {
   AsyDataWithCmpSafe1 value;
} Rte_DE_AsyDataWithCmpSafe1;

typedef struct {
   AsyLatCtrlModReqGroupSafe1 value;
} Rte_DE_AsyLatCtrlModReqGroupSafe1;

typedef struct {
   AsyRoadCrvt0 value;
} Rte_DE_AsyRoadCrvt0;

typedef struct {
   AsyRoadInclPred0 value;
} Rte_DE_AsyRoadInclPred0;

typedef struct {
   AsySftyBrkDlyEstimd0 value;
} Rte_DE_AsySftyBrkDlyEstimd0;

typedef struct {
   AsySftyDecelEnadByVehDyn0 value;
} Rte_DE_AsySftyDecelEnadByVehDyn0;

typedef struct {
   AsySpdMaxPred0 value;
} Rte_DE_AsySpdMaxPred0;

typedef struct {
   AsySpdMinPred0 value;
} Rte_DE_AsySpdMinPred0;

typedef struct {
   AutFctActv0 value;
} Rte_DE_AutFctActv0;

typedef struct {
   AxleSlipRelAct0 value;
} Rte_DE_AxleSlipRelAct0;

typedef struct {
   BkpOfDstTrvld0 value;
} Rte_DE_BkpOfDstTrvld0;

typedef struct {
   BltLockStFrnt value;
} Rte_DE_BltLockStFrnt;

typedef struct {
   BltLockStRe value;
} Rte_DE_BltLockStRe;

typedef struct {
   BltReqFromVehDyn0 value;
} Rte_DE_BltReqFromVehDyn0;

typedef struct {
   BrkAndAbsWarnIndcnReq0 value;
} Rte_DE_BrkAndAbsWarnIndcnReq0;

typedef struct {
   BrkBoostVolFlowReq0 value;
} Rte_DE_BrkBoostVolFlowReq0;

typedef struct {
   BrkByWireWarnIndcn0 value;
} Rte_DE_BrkByWireWarnIndcn0;

typedef struct {
   BrkFldSnsrWdAvl0 value;
} Rte_DE_BrkFldSnsrWdAvl0;

typedef struct {
   BrkFricTqAtWhlActRec value;
} Rte_DE_BrkFricTqAtWhlActRec;

typedef struct {
   BrkFricTqTotAtWhlsActRec1 value;
} Rte_DE_BrkFricTqTotAtWhlsActRec1;

typedef struct {
   BrkHptcStsSafe0 value;
} Rte_DE_BrkHptcStsSafe0;

typedef struct {
   BrkLiOnReq0 value;
} Rte_DE_BrkLiOnReq0;

typedef struct {
   BrkMsgForHybWarnReq0 value;
} Rte_DE_BrkMsgForHybWarnReq0;

typedef struct {
   BrkMsgWarnReq0 value;
} Rte_DE_BrkMsgWarnReq0;

typedef struct {
   BrkPedlPsdRec value;
} Rte_DE_BrkPedlPsdRec;

typedef struct {
   BrkPedlVal0 value;
} Rte_DE_BrkPedlVal0;

typedef struct {
   BrkSysCylPMst0 value;
} Rte_DE_BrkSysCylPMst0;

typedef struct {
   BrkSysWarnIndcnReq0 value;
} Rte_DE_BrkSysWarnIndcnReq0;

typedef struct {
   BrkTqAtWhlsReq0 value;
} Rte_DE_BrkTqAtWhlsReq0;

typedef struct {
   CCPFrameResp0 value;
} Rte_DE_CCPFrameResp0;

typedef struct {
   CarCfgPrmAirSuspDT value;
} Rte_DE_CarCfgPrmAirSuspDT;

typedef struct {
   CarCfgPrmContnslyCtrldDampgDT value;
} Rte_DE_CarCfgPrmContnslyCtrldDampgDT;

typedef struct {
   CarCfgPrmEngTypDT value;
} Rte_DE_CarCfgPrmEngTypDT;

typedef struct {
   CarCfgPrmFuTypDT value;
} Rte_DE_CarCfgPrmFuTypDT;

typedef struct {
   CarCfgPrmGbxTypDT value;
} Rte_DE_CarCfgPrmGbxTypDT;

typedef struct {
   CarCfgPrmGnssRxr0 value;
} Rte_DE_CarCfgPrmGnssRxr0;

typedef struct {
   CarCfgPrmLvlSnsr0 value;
} Rte_DE_CarCfgPrmLvlSnsr0;

typedef struct {
   CarCfgPrmTireSizeDT value;
} Rte_DE_CarCfgPrmTireSizeDT;

typedef struct {
   CarCfgPrmTowBarDT value;
} Rte_DE_CarCfgPrmTowBarDT;

typedef struct {
   CarCfgPrmVehTypDT value;
} Rte_DE_CarCfgPrmVehTypDT;

typedef struct {
   CarCfgPrmiTPMSSysDT value;
} Rte_DE_CarCfgPrmiTPMSSysDT;

typedef struct {
   CarCfgVehSpdMax0 value;
} Rte_DE_CarCfgVehSpdMax0;

typedef struct {
   ChassisCntrForMissCom0 value;
} Rte_DE_ChassisCntrForMissCom0;

typedef struct {
   CluPedlPsd0 value;
} Rte_DE_CluPedlPsd0;

typedef struct {
   CluPedlRat0 value;
} Rte_DE_CluPedlRat0;

typedef struct {
   CrsCtrlALgtMinReq0 value;
} Rte_DE_CrsCtrlALgtMinReq0;

typedef struct {
   CrsCtrlALgtSetReq0 value;
} Rte_DE_CrsCtrlALgtSetReq0;

typedef struct {
   CrsCtrlALgtSoftMaxReq0 value;
} Rte_DE_CrsCtrlALgtSoftMaxReq0;

typedef struct {
   CrsCtrlSpdMaxPred0 value;
} Rte_DE_CrsCtrlSpdMaxPred0;

typedef struct {
   CrsCtrlSpdMinPred0 value;
} Rte_DE_CrsCtrlSpdMinPred0;

typedef struct {
   CrsCtrlrSts1 value;
} Rte_DE_CrsCtrlrSts1;

typedef struct {
   CtrlSts1 value;
} Rte_DE_CtrlSts1;

typedef struct {
   DevErrSts2 value;
} Rte_DE_DevErrSts2;

typedef struct {
   DispMsgByVehHld1WdDispMsg0 value;
} Rte_DE_DispMsgByVehHld1WdDispMsg0;

typedef struct {
   DoorSts2 value;
} Rte_DE_DoorSts2;

typedef struct {
   DrvModReq0 value;
} Rte_DE_DrvModReq0;

typedef struct {
   DrvrBrkTqAtWhlsGrdtReqd0 value;
} Rte_DE_DrvrBrkTqAtWhlsGrdtReqd0;

typedef struct {
   DrvrBrkTqAtWhlsReqdRec1 value;
} Rte_DE_DrvrBrkTqAtWhlsReqdRec1;

typedef struct {
   DrvrDesDir1 value;
} Rte_DE_DrvrDesDir1;

typedef struct {
   DrvrPrpsnTqReq0 value;
} Rte_DE_DrvrPrpsnTqReq0;

typedef struct {
   DstTrvldFromBrkBkp0 value;
} Rte_DE_DstTrvldFromBrkBkp0;

typedef struct {
   DtEngdSt0 value;
} Rte_DE_DtEngdSt0;

typedef struct {
   DynCalBodyRollJ0 value;
} Rte_DE_DynCalBodyRollJ0;

typedef struct {
   DynCalBodyYawJ0 value;
} Rte_DE_DynCalBodyYawJ0;

typedef struct {
   DynCalBodyYawRollJ0 value;
} Rte_DE_DynCalBodyYawRollJ0;

typedef struct {
   DynCalCornrgComplFrnt0 value;
} Rte_DE_DynCalCornrgComplFrnt0;

typedef struct {
   DynCalCornrgComplRe0 value;
} Rte_DE_DynCalCornrgComplRe0;

typedef struct {
   DynCalCornrgStfnFrnt0 value;
} Rte_DE_DynCalCornrgStfnFrnt0;

typedef struct {
   DynCalCornrgStfnRe0 value;
} Rte_DE_DynCalCornrgStfnRe0;

typedef struct {
   DynCalCurbWght0 value;
} Rte_DE_DynCalCurbWght0;

typedef struct {
   DynCalDistCogToFrnt0 value;
} Rte_DE_DynCalDistCogToFrnt0;

typedef struct {
   DynCalDistCogToRe0 value;
} Rte_DE_DynCalDistCogToRe0;

typedef struct {
   DynCalDistRollAxleToCog0 value;
} Rte_DE_DynCalDistRollAxleToCog0;

typedef struct {
   DynCalDrgCoeff0 value;
} Rte_DE_DynCalDrgCoeff0;

typedef struct {
   DynCalDrgHei0 value;
} Rte_DE_DynCalDrgHei0;

typedef struct {
   DynCalFrntAr0 value;
} Rte_DE_DynCalFrntAr0;

typedef struct {
   DynCalFrntRiRbdU0 value;
} Rte_DE_DynCalFrntRiRbdU0;

typedef struct {
   DynCalFrntVoltToMtrCnvnFac0 value;
} Rte_DE_DynCalFrntVoltToMtrCnvnFac0;

typedef struct {
   DynCalHeiCog0 value;
} Rte_DE_DynCalHeiCog0;

typedef struct {
   DynCalLatLoadShiftGrdtFrnt0 value;
} Rte_DE_DynCalLatLoadShiftGrdtFrnt0;

typedef struct {
   DynCalLatLoadShiftGrdtRe0 value;
} Rte_DE_DynCalLatLoadShiftGrdtRe0;

typedef struct {
   DynCalLgtSlipCmpConFrnt0 value;
} Rte_DE_DynCalLgtSlipCmpConFrnt0;

typedef struct {
   DynCalLgtSlipCmpConRe0 value;
} Rte_DE_DynCalLgtSlipCmpConRe0;

typedef struct {
   DynCalPitchAGrdt0 value;
} Rte_DE_DynCalPitchAGrdt0;

typedef struct {
   DynCalPitchDecelGrdt0 value;
} Rte_DE_DynCalPitchDecelGrdt0;

typedef struct {
   DynCalReRiRbdU0 value;
} Rte_DE_DynCalReRiRbdU0;

typedef struct {
   DynCalReVoltToMtrCnvnFac0 value;
} Rte_DE_DynCalReVoltToMtrCnvnFac0;

typedef struct {
   DynCalRollACoeff0 value;
} Rte_DE_DynCalRollACoeff0;

typedef struct {
   DynCalRollAgGrdt0 value;
} Rte_DE_DynCalRollAgGrdt0;

typedef struct {
   DynCalRollCenterHeiFrnt0 value;
} Rte_DE_DynCalRollCenterHeiFrnt0;

typedef struct {
   DynCalRollCenterHeiRe0 value;
} Rte_DE_DynCalRollCenterHeiRe0;

typedef struct {
   DynCalRollDampgCoeff0 value;
} Rte_DE_DynCalRollDampgCoeff0;

typedef struct {
   DynCalRollSprgCoeff0 value;
} Rte_DE_DynCalRollSprgCoeff0;

typedef struct {
   DynCalRollSteerCoeffFrnt0 value;
} Rte_DE_DynCalRollSteerCoeffFrnt0;

typedef struct {
   DynCalRollSteerCoeffRe0 value;
} Rte_DE_DynCalRollSteerCoeffRe0;

typedef struct {
   DynCalRollStfnFrnt0 value;
} Rte_DE_DynCalRollStfnFrnt0;

typedef struct {
   DynCalRollStfnRe0 value;
} Rte_DE_DynCalRollStfnRe0;

typedef struct {
   DynCalSteerRat0 value;
} Rte_DE_DynCalSteerRat0;

typedef struct {
   DynCalTireLgtStfnFrnt0 value;
} Rte_DE_DynCalTireLgtStfnFrnt0;

typedef struct {
   DynCalTireLgtStfnRe0 value;
} Rte_DE_DynCalTireLgtStfnRe0;

typedef struct {
   DynCalTireRelaxationLen0 value;
} Rte_DE_DynCalTireRelaxationLen0;

typedef struct {
   DynCalTrkWidthFrnt0 value;
} Rte_DE_DynCalTrkWidthFrnt0;

typedef struct {
   DynCalTrkWidthRe0 value;
} Rte_DE_DynCalTrkWidthRe0;

typedef struct {
   DynCalVehMSprung0 value;
} Rte_DE_DynCalVehMSprung0;

typedef struct {
   DynCalVehMUnsprung0 value;
} Rte_DE_DynCalVehMUnsprung0;

typedef struct {
   DynCalWhlBas0 value;
} Rte_DE_DynCalWhlBas0;

typedef struct {
   DynCalWhlJ0 value;
} Rte_DE_DynCalWhlJ0;

typedef struct {
   DynCalWhlRd0 value;
} Rte_DE_DynCalWhlRd0;

typedef struct {
   DynCalWhlRdStatLoaded0 value;
} Rte_DE_DynCalWhlRdStatLoaded0;

typedef struct {
   DynModOfPtReq0 value;
} Rte_DE_DynModOfPtReq0;

typedef struct {
   EMASteerTqReq0 value;
} Rte_DE_EMASteerTqReq0;

typedef struct {
   EmgyBrkLiReq0 value;
} Rte_DE_EmgyBrkLiReq0;

typedef struct {
   EngCooltSnsrWdAvl0 value;
} Rte_DE_EngCooltSnsrWdAvl0;

typedef struct {
   EngNSafe0 value;
} Rte_DE_EngNSafe0;

typedef struct {
   EngRunngReqByBrk0 value;
} Rte_DE_EngRunngReqByBrk0;

typedef struct {
   EpbBtnCtrlSt0 value;
} Rte_DE_EpbBtnCtrlSt0;

typedef struct {
   EpbDrvrDisp1WdDrvrDisp0 value;
} Rte_DE_EpbDrvrDisp1WdDrvrDisp0;

typedef struct {
   EpbLampReq0 value;
} Rte_DE_EpbLampReq0;

typedef struct {
   EpbStsRec1 value;
} Rte_DE_EpbStsRec1;

typedef struct {
   EpbStsRec1E2E value;
} Rte_DE_EpbStsRec1E2E;

typedef struct {
   EscCtrlIndcn0 value;
} Rte_DE_EscCtrlIndcn0;

typedef struct {
   EscDamprReq0 value;
} Rte_DE_EscDamprReq0;

typedef struct {
   EscGearShiftInhbReq0 value;
} Rte_DE_EscGearShiftInhbReq0;

typedef struct {
   EscSt0 value;
} Rte_DE_EscSt0;

typedef struct {
   EscWarnIndcnReq0 value;
} Rte_DE_EscWarnIndcnReq0;

typedef struct {
   Fac31 value;
} Rte_DE_Fac31;

typedef struct {
   Flg1 value;
} Rte_DE_Flg1;

typedef struct {
   FrntSteerFEstimd10 value;
} Rte_DE_FrntSteerFEstimd10;

typedef struct {
   FuLvlValWithQly value;
} Rte_DE_FuLvlValWithQly;

typedef struct {
   GenQf1 value;
} Rte_DE_GenQf1;

typedef struct {
   ImobBrkNrSerl0 value;
} Rte_DE_ImobBrkNrSerl0;

typedef struct {
   IndcnToDrvrPostImpctCtrl0 value;
} Rte_DE_IndcnToDrvrPostImpctCtrl0;

typedef struct {
   InhbOfAsySftyDecelByVehDyn0 value;
} Rte_DE_InhbOfAsySftyDecelByVehDyn0;

typedef struct {
   InvldVld1 value;
} Rte_DE_InvldVld1;

typedef struct {
   KL30Voltage0 value;
} Rte_DE_KL30Voltage0;

typedef struct {
   LampReqByVehHld1WdLampReq0 value;
} Rte_DE_LampReqByVehHld1WdLampReq0;

typedef struct {
   LatCtrlMod3 value;
} Rte_DE_LatCtrlMod3;

typedef struct {
   LimForDecel0 value;
} Rte_DE_LimForDecel0;

typedef struct {
   LimForJerkPosNotExcd0 value;
} Rte_DE_LimForJerkPosNotExcd0;

typedef struct {
   MsgReqByHillDwnCtrl0 value;
} Rte_DE_MsgReqByHillDwnCtrl0;

typedef struct {
   MstCfgIDChassisCAN0 value;
} Rte_DE_MstCfgIDChassisCAN0;

typedef struct {
   MstCfgIDPropulsionCAN0 value;
} Rte_DE_MstCfgIDPropulsionCAN0;

typedef struct {
   MtnMdlResi0 value;
} Rte_DE_MtnMdlResi0;

typedef struct {
   NoYes1 value;
} Rte_DE_NoYes1;

typedef struct {
   OnOff1 value;
} Rte_DE_OnOff1;

typedef struct {
   OvrSpdLimALgtMinReq0 value;
} Rte_DE_OvrSpdLimALgtMinReq0;

typedef struct {
   OvrSpdLimALgtSetReq0 value;
} Rte_DE_OvrSpdLimALgtSetReq0;

typedef struct {
   OvrSpdLimALgtSoftMaxReq0 value;
} Rte_DE_OvrSpdLimALgtSoftMaxReq0;

typedef struct {
   PVac0 value;
} Rte_DE_PVac0;

typedef struct {
   PedlFCompCtrlSt0 value;
} Rte_DE_PedlFCompCtrlSt0;

typedef struct {
   Perc1 value;
} Rte_DE_Perc1;

typedef struct {
   PinionSteerAg1Rec value;
} Rte_DE_PinionSteerAg1Rec;

typedef struct {
   PinionSteerAgSpd1Rec value;
} Rte_DE_PinionSteerAgSpd1Rec;

typedef struct {
   PosnFromSatlt0 value;
} Rte_DE_PosnFromSatlt0;

typedef struct {
   PropulsionTyp value;
} Rte_DE_PropulsionTyp;

typedef struct {
   PrpsnCntrForMissCom0 value;
} Rte_DE_PrpsnCntrForMissCom0;

typedef struct {
   PrpsnTqForBrkRelsToVehDyn0 value;
} Rte_DE_PrpsnTqForBrkRelsToVehDyn0;

typedef struct {
   PtActrReModReq0 value;
} Rte_DE_PtActrReModReq0;

typedef struct {
   PtBrkTqReq0 value;
} Rte_DE_PtBrkTqReq0;

typedef struct {
   PtGearAct0 value;
} Rte_DE_PtGearAct0;

typedef struct {
   PtSetALgtReq0 value;
} Rte_DE_PtSetALgtReq0;

typedef struct {
   PtTqAtAxleAddReq0 value;
} Rte_DE_PtTqAtAxleAddReq0;

typedef struct {
   PtTqAtAxleFrntMaxReq0 value;
} Rte_DE_PtTqAtAxleFrntMaxReq0;

typedef struct {
   PtTqAtAxleFrntMinReq0 value;
} Rte_DE_PtTqAtAxleFrntMinReq0;

typedef struct {
   PtTqAtAxleReMaxReq0 value;
} Rte_DE_PtTqAtAxleReMaxReq0;

typedef struct {
   PtTqAtAxleReMinReq0 value;
} Rte_DE_PtTqAtAxleReMinReq0;

typedef struct {
   PtTqAtAxleReMinSlowReq0 value;
} Rte_DE_PtTqAtAxleReMinSlowReq0;

typedef struct {
   PtTqAtWhlFrntActRec1 value;
} Rte_DE_PtTqAtWhlFrntActRec1;

typedef struct {
   PtTqAtWhlReActRec1 value;
} Rte_DE_PtTqAtWhlReActRec1;

typedef struct {
   PtTqTotDrgAtWhls0 value;
} Rte_DE_PtTqTotDrgAtWhls0;

typedef struct {
   PtVehSpdMax0 value;
} Rte_DE_PtVehSpdMax0;

typedef struct {
   ReqSts1 value;
} Rte_DE_ReqSts1;

typedef struct {
   RoadInclnRec1 value;
} Rte_DE_RoadInclnRec1;

typedef struct {
   RoadLoadNom0 value;
} Rte_DE_RoadLoadNom0;

typedef struct {
   RscResdSigToVehDynCtrl100 value;
} Rte_DE_RscResdSigToVehDynCtrl100;

typedef struct {
   RscResdSigToVehDynCtrl10x value;
} Rte_DE_RscResdSigToVehDynCtrl10x;

typedef struct {
   RscResdSigToVehDynCtrl110 value;
} Rte_DE_RscResdSigToVehDynCtrl110;

typedef struct {
   RscResdSigToVehDynCtrl120 value;
} Rte_DE_RscResdSigToVehDynCtrl120;

typedef struct {
   RscResdSigToVehDynCtrl130 value;
} Rte_DE_RscResdSigToVehDynCtrl130;

typedef struct {
   RscResdSigToVehDynCtrl140 value;
} Rte_DE_RscResdSigToVehDynCtrl140;

typedef struct {
   RscResdSigToVehDynCtrl150 value;
} Rte_DE_RscResdSigToVehDynCtrl150;

typedef struct {
   RscResdSigToVehDynCtrl160 value;
} Rte_DE_RscResdSigToVehDynCtrl160;

typedef struct {
   RscResdSigToVehDynCtrl170 value;
} Rte_DE_RscResdSigToVehDynCtrl170;

typedef struct {
   RscResdSigToVehDynCtrl180 value;
} Rte_DE_RscResdSigToVehDynCtrl180;

typedef struct {
   RscResdSigToVehDynCtrl190 value;
} Rte_DE_RscResdSigToVehDynCtrl190;

typedef struct {
   RscResdSigToVehDynCtrl200 value;
} Rte_DE_RscResdSigToVehDynCtrl200;

typedef struct {
   RscResdSigToVehDynCtrl20x value;
} Rte_DE_RscResdSigToVehDynCtrl20x;

typedef struct {
   RscResdSigToVehDynCtrl210 value;
} Rte_DE_RscResdSigToVehDynCtrl210;

typedef struct {
   RscResdSigToVehDynCtrl220 value;
} Rte_DE_RscResdSigToVehDynCtrl220;

typedef struct {
   RscResdSigToVehDynCtrl230 value;
} Rte_DE_RscResdSigToVehDynCtrl230;

typedef struct {
   RscResdSigToVehDynCtrl240 value;
} Rte_DE_RscResdSigToVehDynCtrl240;

typedef struct {
   RscResdSigToVehDynCtrl250 value;
} Rte_DE_RscResdSigToVehDynCtrl250;

typedef struct {
   RscResdSigToVehDynCtrl260 value;
} Rte_DE_RscResdSigToVehDynCtrl260;

typedef struct {
   RscResdSigToVehDynCtrl270 value;
} Rte_DE_RscResdSigToVehDynCtrl270;

typedef struct {
   RscResdSigToVehDynCtrl280 value;
} Rte_DE_RscResdSigToVehDynCtrl280;

typedef struct {
   RscResdSigToVehDynCtrl290 value;
} Rte_DE_RscResdSigToVehDynCtrl290;

typedef struct {
   RscResdSigToVehDynCtrl300 value;
} Rte_DE_RscResdSigToVehDynCtrl300;

typedef struct {
   RscResdSigToVehDynCtrl30x value;
} Rte_DE_RscResdSigToVehDynCtrl30x;

typedef struct {
   RscResdSigToVehDynCtrl310 value;
} Rte_DE_RscResdSigToVehDynCtrl310;

typedef struct {
   RscResdSigToVehDynCtrl320 value;
} Rte_DE_RscResdSigToVehDynCtrl320;

typedef struct {
   RscResdSigToVehDynCtrl330 value;
} Rte_DE_RscResdSigToVehDynCtrl330;

typedef struct {
   RscResdSigToVehDynCtrl340 value;
} Rte_DE_RscResdSigToVehDynCtrl340;

typedef struct {
   RscResdSigToVehDynCtrl350 value;
} Rte_DE_RscResdSigToVehDynCtrl350;

typedef struct {
   RscResdSigToVehDynCtrl360 value;
} Rte_DE_RscResdSigToVehDynCtrl360;

typedef struct {
   RscResdSigToVehDynCtrl40 value;
} Rte_DE_RscResdSigToVehDynCtrl40;

typedef struct {
   RscResdSigToVehDynCtrl50 value;
} Rte_DE_RscResdSigToVehDynCtrl50;

typedef struct {
   RscResdSigToVehDynCtrl60 value;
} Rte_DE_RscResdSigToVehDynCtrl60;

typedef struct {
   RscResdSigToVehDynCtrl70 value;
} Rte_DE_RscResdSigToVehDynCtrl70;

typedef struct {
   RscResdSigToVehDynCtrl80 value;
} Rte_DE_RscResdSigToVehDynCtrl80;

typedef struct {
   RscResdSigToVehDynCtrl90 value;
} Rte_DE_RscResdSigToVehDynCtrl90;

typedef struct {
   SetALgtReq0 value;
} Rte_DE_SetALgtReq0;

typedef struct {
   SetSpdForCrsCtrlFct0 value;
} Rte_DE_SetSpdForCrsCtrlFct0;

typedef struct {
   SetSpdForKeySpdLimn0 value;
} Rte_DE_SetSpdForKeySpdLimn0;

typedef struct {
   SnsrCfg0 value;
} Rte_DE_SnsrCfg0;

typedef struct {
   SnsrForLvlSuspPosnVertFrnt0 value;
} Rte_DE_SnsrForLvlSuspPosnVertFrnt0;

typedef struct {
   SnsrForLvlSuspPosnVertRe0 value;
} Rte_DE_SnsrForLvlSuspPosnVertRe0;

typedef struct {
   SnsrForLvlWdSplyStRec value;
} Rte_DE_SnsrForLvlWdSplyStRec;

typedef struct {
   SnsrForLvlWdVehLvlRec value;
} Rte_DE_SnsrForLvlWdVehLvlRec;

typedef struct {
   SpdLimALgtHardMaxReq0 value;
} Rte_DE_SpdLimALgtHardMaxReq0;

typedef struct {
   SpdRotlForWhlsAtAxleFrntSafe0 value;
} Rte_DE_SpdRotlForWhlsAtAxleFrntSafe0;

typedef struct {
   SpdRotlForWhlsAtAxleRe0 value;
} Rte_DE_SpdRotlForWhlsAtAxleRe0;

typedef struct {
   StandStillMgrStsForHld1 value;
} Rte_DE_StandStillMgrStsForHld1;

typedef struct {
   StandStillMgrStsForPark1 value;
} Rte_DE_StandStillMgrStsForPark1;

typedef struct {
   SteerWhlSnsrSafe1 value;
} Rte_DE_SteerWhlSnsrSafe1;

typedef struct {
   SteerWhlTq0 value;
} Rte_DE_SteerWhlTq0;

typedef struct {
   SuspPosnVertLeRec value;
} Rte_DE_SuspPosnVertLeRec;

typedef struct {
   SuspPosnVertRiRec1 value;
} Rte_DE_SuspPosnVertRiRec1;

typedef struct {
   TSts1 value;
} Rte_DE_TSts1;

typedef struct {
   Tq1 value;
} Rte_DE_Tq1;

typedef struct {
   TrlrPrsntSts value;
} Rte_DE_TrlrPrsntSts;

typedef struct {
   TrsmDrvLine value;
} Rte_DE_TrsmDrvLine;

typedef struct {
   TrsmStAxleReActrDT value;
} Rte_DE_TrsmStAxleReActrDT;

typedef struct {
   VehALgt0 value;
} Rte_DE_VehALgt0;

typedef struct {
   VehBattU0 value;
} Rte_DE_VehBattU0;

typedef struct {
   VehCfgPrmDT value;
} Rte_DE_VehCfgPrmDT;

typedef struct {
   VehDynCtrlResdSigToRsc100 value;
} Rte_DE_VehDynCtrlResdSigToRsc100;

typedef struct {
   VehDynCtrlResdSigToRsc110 value;
} Rte_DE_VehDynCtrlResdSigToRsc110;

typedef struct {
   VehDynCtrlResdSigToRsc120 value;
} Rte_DE_VehDynCtrlResdSigToRsc120;

typedef struct {
   VehDynCtrlResdSigToRsc130 value;
} Rte_DE_VehDynCtrlResdSigToRsc130;

typedef struct {
   VehDynCtrlResdSigToRsc140 value;
} Rte_DE_VehDynCtrlResdSigToRsc140;

typedef struct {
   VehDynCtrlResdSigToRsc150 value;
} Rte_DE_VehDynCtrlResdSigToRsc150;

typedef struct {
   VehDynCtrlResdSigToRsc160 value;
} Rte_DE_VehDynCtrlResdSigToRsc160;

typedef struct {
   VehFByDrg0 value;
} Rte_DE_VehFByDrg0;

typedef struct {
   VehMNomRec1 value;
} Rte_DE_VehMNomRec1;

typedef struct {
   VehModMngtGlbSafe1DT value;
} Rte_DE_VehModMngtGlbSafe1DT;

typedef struct {
   VehMtnStFromVehSt0 value;
} Rte_DE_VehMtnStFromVehSt0;

typedef struct {
   VehMtnStSafe1 value;
} Rte_DE_VehMtnStSafe1;

typedef struct {
   VehPitchAgRelToRoad0 value;
} Rte_DE_VehPitchAgRelToRoad0;

typedef struct {
   VehSpdLgtSafe1 value;
} Rte_DE_VehSpdLgtSafe1;

typedef struct {
   VehVSafe1 value;
} Rte_DE_VehVSafe1;

typedef struct {
   WhlBrkPEstimdMax0 value;
} Rte_DE_WhlBrkPEstimdMax0;

typedef struct {
   WhlDirRotlRe0 value;
} Rte_DE_WhlDirRotlRe0;

typedef struct {
   WhlEdgeRisngFrntLe0 value;
} Rte_DE_WhlEdgeRisngFrntLe0;

typedef struct {
   WhlEdgeRisngFrntRi0 value;
} Rte_DE_WhlEdgeRisngFrntRi0;

typedef struct {
   WhlEdgeRisngReLe0 value;
} Rte_DE_WhlEdgeRisngReLe0;

typedef struct {
   WhlEdgeRisngReRi0 value;
} Rte_DE_WhlEdgeRisngReRi0;

typedef struct {
   WhlRdEstimd0 value;
} Rte_DE_WhlRdEstimd0;

typedef struct {
   WhlRotCntrFrnt0 value;
} Rte_DE_WhlRotCntrFrnt0;

typedef struct {
   WhlRotToothCntr0 value;
} Rte_DE_WhlRotToothCntr0;

typedef struct {
   WhlSpdCircumlFrnt0 value;
} Rte_DE_WhlSpdCircumlFrnt0;

typedef struct {
   WhlSpdCircumlRe0 value;
} Rte_DE_WhlSpdCircumlRe0;

typedef struct {
   WhlVAgrFrntRec1 value;
} Rte_DE_WhlVAgrFrntRec1;

typedef struct {
   WhlVAgrReRec1 value;
} Rte_DE_WhlVAgrReRec1;

typedef struct {
   YawRateFromOffsCmp0 value;
} Rte_DE_YawRateFromOffsCmp0;

typedef struct {
   YawRateReqdByDrvr0 value;
} Rte_DE_YawRateReqdByDrvr0;

typedef struct {
   iTPMSCalReq0 value;
} Rte_DE_iTPMSCalReq0;

typedef struct {
   iTPMSIdleMod0 value;
} Rte_DE_iTPMSIdleMod0;

typedef struct {
   iTPMSTirePMSts0 value;
} Rte_DE_iTPMSTirePMSts0;

typedef struct {
   rt_Array_DynCalSteerColAgTbl0_4 value;
} Rte_DE_rt_Array_DynCalSteerColAgTbl0_4;

typedef struct {
   rt_Array_DynCalSteerColRatTbl0_4 value;
} Rte_DE_rt_Array_DynCalSteerColRatTbl0_4;

typedef struct {
   Rte_DE_VehCfgPrmDT                      rbuf0;
   Rte_DE_SetSpdForKeySpdLimn0             rbuf1;
   Rte_DE_AccSts1                          rbuf10;
   Rte_DE_ADataRawSafe1                    rbuf11;
   Rte_DE_AgDataRawSafe1                   rbuf12;
   Rte_DE_AmbTRaw0                         rbuf13;
   Rte_DE_AsyDataWithCmpSafe1              rbuf14;
   Rte_DE_CluPedlPsd0                      rbuf15;
   Rte_DE_CrsCtrlrSts1                     rbuf16;
   Rte_DE_BkpOfDstTrvld0                   rbuf17;
   Rte_DE_DtEngdSt0                        rbuf18;
   Rte_DE_EngNSafe0                        rbuf19;
   Rte_DE_SetSpdForCrsCtrlFct0             rbuf2;
   Rte_DE_PtGearAct0                       rbuf20;
   Rte_DE_PtTqAtWhlFrntActRec1             rbuf21;
   Rte_DE_PtTqAtWhlReActRec1               rbuf22;
   Rte_DE_SteerWhlSnsrSafe1                rbuf23;
   Rte_DE_SuspPosnVertLeRec                rbuf24;
   Rte_DE_SuspPosnVertRiRec1               rbuf25;
   Rte_DE_TrlrPrsntSts                     rbuf26;
   Rte_DE_VehCfgPrmDT                      rbuf27;
   Rte_DE_VehModMngtGlbSafe1DT             rbuf28;
   Rte_DE_AirPInAirSprg0                   rbuf29;
   Rte_DE_PtVehSpdMax0                     rbuf3;
   Rte_DE_AmbTIndcdWithUnit0               rbuf30;
   Rte_DE_iTPMSCalReq0                     rbuf31;
   Rte_DE_iTPMSCalReq0                     rbuf32;
   Rte_DE_Fac31                            rbuf33;
   Rte_DE_VehModMngtGlbSafe1DT             rbuf34;
   Rte_DE_TrsmStAxleReActrDT               rbuf35;
   Rte_DE_DoorSts2                         rbuf36;
   Rte_DE_SteerWhlTq0                      rbuf37;
   Rte_DE_PtTqAtWhlReActRec1               rbuf38;
   Rte_DE_PtTqAtWhlFrntActRec1             rbuf39;
   Rte_DE_PtTqTotDrgAtWhls0                rbuf4;
   Rte_DE_PtGearAct0                       rbuf40;
   Rte_DE_PosnFromSatlt0                   rbuf41;
   Rte_DE_PinionSteerAgSpd1Rec             rbuf42;
   Rte_DE_PinionSteerAg1Rec                rbuf43;
   Rte_DE_Flg1                             rbuf44;
   Rte_DE_FuLvlValWithQly                  rbuf45;
   Rte_DE_FrntSteerFEstimd10               rbuf46;
   Rte_DE_EngNSafe0                        rbuf47;
   Rte_DE_DtEngdSt0                        rbuf48;
   Rte_DE_DrvrDesDir1                      rbuf49;
   Rte_DE_DrvrPrpsnTqReq0                  rbuf5;
   Rte_DE_DoorSts2                         rbuf50;
   Rte_DE_DoorSts2                         rbuf51;
   Rte_DE_DoorSts2                         rbuf52;
   Rte_DE_DoorSts2                         rbuf53;
   Rte_DE_CluPedlRat0                      rbuf54;
   Rte_DE_BrkPedlVal0                      rbuf55;
   Rte_DE_BltLockStRe                      rbuf56;
   Rte_DE_BltLockStRe                      rbuf57;
   Rte_DE_BltLockStRe                      rbuf58;
   Rte_DE_BltLockStRe                      rbuf59;
   Rte_DE_DrvModReq0                       rbuf6;
   Rte_DE_BltLockStRe                      rbuf60;
   Rte_DE_BltLockStFrnt                    rbuf61;
   Rte_DE_BltLockStFrnt                    rbuf62;
   Rte_DE_AmbTRaw0                         rbuf63;
   Rte_DE_Perc1                            rbuf64;
   Rte_DE_AccrPedlPsdSafe1                 rbuf65;
   Rte_DE_TrlrPrsntSts                     rbuf66;
   Rte_DE_OnOff1                           rbuf67;
   Rte_DE_AsySpdMinPred0                   rbuf68;
   Rte_DE_AsySpdMaxPred0                   rbuf69;
   Rte_DE_CrsCtrlrSts1                     rbuf7;
   Rte_DE_AsyRoadInclPred0                 rbuf70;
   Rte_DE_AsyALgtRespAndLim1               rbuf71;
   Rte_DE_AsyALgtReqRngForCmft0            rbuf72;
   Rte_DE_SuspPosnVertLeRec                rbuf73;
   Rte_DE_PtTqAtWhlReActRec1               rbuf74;
   Rte_DE_PtTqAtWhlFrntActRec1             rbuf75;
   Rte_DE_PtGearAct0                       rbuf76;
   Rte_DE_EngNSafe0                        rbuf77;
   Rte_DE_DrvrPrpsnTqReq0                  rbuf78;
   Rte_DE_VehModMngtGlbSafe1DT             rbuf79;
   Rte_DE_OnOff1                           rbuf8;
   Rte_DE_VehBattU0                        rbuf80;
   Rte_DE_SteerWhlSnsrSafe1                rbuf81;
   Rte_DE_AsyLatCtrlModReqGroupSafe1       rbuf82;
   Rte_DE_AsyRoadCrvt0                     rbuf83;
   Rte_DE_A33                              rbuf84;
   Rte_DE_AdjSpdLimnSts2                   rbuf9;
   Rte_DE_DynCalRollStfnFrnt0              sbuf100;
   Rte_DE_DynCalRollSteerCoeffRe0          sbuf101;
   Rte_DE_DynCalRollSteerCoeffFrnt0        sbuf102;
   Rte_DE_DynCalRollSprgCoeff0             sbuf103;
   Rte_DE_DynCalRollDampgCoeff0            sbuf104;
   Rte_DE_DynCalRollCenterHeiRe0           sbuf105;
   Rte_DE_DynCalRollCenterHeiFrnt0         sbuf106;
   Rte_DE_DynCalRollAgGrdt0                sbuf107;
   Rte_DE_DynCalRollACoeff0                sbuf108;
   Rte_DE_DynCalReVoltToMtrCnvnFac0        sbuf109;
   Rte_DE_DynCalReRiRbdU0                  sbuf110;
   Rte_DE_DynCalPitchDecelGrdt0            sbuf111;
   Rte_DE_DynCalPitchAGrdt0                sbuf112;
   Rte_DE_DynCalLgtSlipCmpConRe0           sbuf113;
   Rte_DE_DynCalLgtSlipCmpConFrnt0         sbuf114;
   Rte_DE_DynCalLatLoadShiftGrdtRe0        sbuf115;
   Rte_DE_DynCalLatLoadShiftGrdtFrnt0      sbuf116;
   Rte_DE_DynCalHeiCog0                    sbuf117;
   Rte_DE_DynCalFrntVoltToMtrCnvnFac0      sbuf118;
   Rte_DE_DynCalFrntRiRbdU0                sbuf119;
   Rte_DE_DynCalFrntAr0                    sbuf120;
   Rte_DE_DynCalDrgHei0                    sbuf121;
   Rte_DE_DynCalDrgCoeff0                  sbuf122;
   Rte_DE_DynCalDistRollAxleToCog0         sbuf123;
   Rte_DE_DynCalDistCogToRe0               sbuf124;
   Rte_DE_DynCalDistCogToFrnt0             sbuf125;
   Rte_DE_DynCalCurbWght0                  sbuf126;
   Rte_DE_DynCalCornrgStfnRe0              sbuf127;
   Rte_DE_DynCalCornrgStfnFrnt0            sbuf128;
   Rte_DE_DynCalCornrgComplRe0             sbuf129;
   Rte_DE_DynCalCornrgComplFrnt0           sbuf130;
   Rte_DE_DynCalBodyYawRollJ0              sbuf131;
   Rte_DE_DynCalBodyYawJ0                  sbuf132;
   Rte_DE_DynCalBodyRollJ0                 sbuf133;
   Rte_DE_CarCfgVehSpdMax0                 sbuf134;
   Rte_DE_CarCfgPrmiTPMSSysDT              sbuf135;
   Rte_DE_CarCfgPrmVehTypDT                sbuf136;
   Rte_DE_TrsmDrvLine                      sbuf137;
   Rte_DE_CarCfgPrmTowBarDT                sbuf138;
   Rte_DE_CarCfgPrmTireSizeDT              sbuf139;
   Rte_DE_PropulsionTyp                    sbuf140;
   Rte_DE_CarCfgPrmLvlSnsr0                sbuf141;
   Rte_DE_CarCfgPrmGnssRxr0                sbuf142;
   Rte_DE_CarCfgPrmGbxTypDT                sbuf143;
   Rte_DE_CarCfgPrmFuTypDT                 sbuf144;
   Rte_DE_CarCfgPrmEngTypDT                sbuf145;
   Rte_DE_CarCfgPrmContnslyCtrldDampgDT    sbuf146;
   Rte_DE_CarCfgPrmAirSuspDT               sbuf147;
   Rte_DE_NoYes1                           sbuf148;
   Rte_DE_SpdLimALgtHardMaxReq0            sbuf149;
   Rte_DE_OvrSpdLimALgtSoftMaxReq0         sbuf150;
   Rte_DE_OvrSpdLimALgtSetReq0             sbuf151;
   Rte_DE_OvrSpdLimALgtMinReq0             sbuf152;
   Rte_DE_CrsCtrlSpdMinPred0               sbuf153;
   Rte_DE_CrsCtrlSpdMaxPred0               sbuf154;
   Rte_DE_CrsCtrlALgtSoftMaxReq0           sbuf155;
   Rte_DE_CrsCtrlALgtSetReq0               sbuf156;
   Rte_DE_CrsCtrlALgtMinReq0               sbuf157;
   Rte_DE_WhlRdEstimd0                     sbuf158;
   Rte_DE_VehVSafe1                        sbuf159;
   Rte_DE_VehMNomRec1                      sbuf160;
   Rte_DE_VehALgt0                         sbuf161;
   Rte_DE_RoadLoadNom0                     sbuf162;
   Rte_DE_MtnMdlResi0                      sbuf163;
   Rte_DE_BrkPedlPsdRec                    sbuf164;
   Rte_DE_CtrlSts1                         sbuf165;
   Rte_DE_AbsCtrlActvForWhlRec1            sbuf166;
   Rte_DE_BrkFricTqAtWhlActRec             sbuf167;
   Rte_DE_BrkTqAtWhlsReq0                  sbuf168;
   Rte_DE_EpbStsRec1E2E                    sbuf169;
   Rte_DE_EscCtrlIndcn0                    sbuf170;
   Rte_DE_VehMtnStSafe1                    sbuf171;
   Rte_DE_VehSpdLgtSafe1                   sbuf172;
   Rte_DE_WhlDirRotlRe0                    sbuf173;
   Rte_DE_WhlRotToothCntr0                 sbuf174;
   Rte_DE_SnsrForLvlWdVehLvlRec            sbuf175;
   Rte_DE_WhlEdgeRisngFrntLe0              sbuf176;
   Rte_DE_WhlEdgeRisngFrntRi0              sbuf177;
   Rte_DE_WhlEdgeRisngReLe0                sbuf178;
   Rte_DE_WhlEdgeRisngReRi0                sbuf179;
   Rte_DE_iTPMSIdleMod0                    sbuf180;
   Rte_DE_YawRateFromOffsCmp0              sbuf181;
   Rte_DE_VehPitchAgRelToRoad0             sbuf182;
   Rte_DE_VehMtnStFromVehSt0               sbuf183;
   Rte_DE_VehFByDrg0                       sbuf184;
   Rte_DE_ALgtFromOffsCmpRec               sbuf185;
   Rte_DE_ALatFromOffsCmp0                 sbuf186;
   Rte_DE_iTPMSTirePMSts0                  sbuf187;
   Rte_DE_CtrlSts1                         sbuf188;
   Rte_DE_CtrlSts1                         sbuf189;
   Rte_DE_CtrlSts1                         sbuf190;
   Rte_DE_CtrlSts1                         sbuf191;
   Rte_DE_CtrlSts1                         sbuf192;
   Rte_DE_RscResdSigToVehDynCtrl60         sbuf193;
   Rte_DE_RscResdSigToVehDynCtrl50         sbuf194;
   Rte_DE_RscResdSigToVehDynCtrl40         sbuf195;
   Rte_DE_RscResdSigToVehDynCtrl260        sbuf196;
   Rte_DE_RscResdSigToVehDynCtrl250        sbuf197;
   Rte_DE_RscResdSigToVehDynCtrl240        sbuf198;
   Rte_DE_RscResdSigToVehDynCtrl230        sbuf199;
   Rte_DE_RscResdSigToVehDynCtrl220        sbuf200;
   Rte_DE_RscResdSigToVehDynCtrl210        sbuf201;
   Rte_DE_RscResdSigToVehDynCtrl190        sbuf202;
   Rte_DE_RscResdSigToVehDynCtrl180        sbuf203;
   Rte_DE_RscResdSigToVehDynCtrl170        sbuf204;
   Rte_DE_RscResdSigToVehDynCtrl160        sbuf205;
   Rte_DE_RscResdSigToVehDynCtrl150        sbuf206;
   Rte_DE_RscResdSigToVehDynCtrl140        sbuf207;
   Rte_DE_RscResdSigToVehDynCtrl130        sbuf208;
   Rte_DE_RscResdSigToVehDynCtrl120        sbuf209;
   Rte_DE_CtrlSts1                         sbuf210;
   Rte_DE_CtrlSts1                         sbuf211;
   Rte_DE_CtrlSts1                         sbuf212;
   Rte_DE_CtrlSts1                         sbuf213;
   Rte_DE_CtrlSts1                         sbuf214;
   Rte_DE_CtrlSts1                         sbuf215;
   Rte_DE_CtrlSts1                         sbuf216;
   Rte_DE_CtrlSts1                         sbuf217;
   Rte_DE_CtrlSts1                         sbuf218;
   Rte_DE_CtrlSts1                         sbuf219;
   Rte_DE_CtrlSts1                         sbuf220;
   Rte_DE_CtrlSts1                         sbuf221;
   Rte_DE_ALgtStdFromWhlSpdSafe1           sbuf222;
   Rte_DE_DevErrSts2                       sbuf223;
   Rte_DE_EMASteerTqReq0                   sbuf224;
   Rte_DE_NoYes1                           sbuf225;
   Rte_DE_SetALgtReq0                      sbuf226;
   Rte_DE_NoYes1                           sbuf227;
   Rte_DE_PtSetALgtReq0                    sbuf228;
   Rte_DE_ReqSts1                          sbuf229;
   Rte_DE_DevErrSts2                       sbuf230;
   Rte_DE_AutFctActv0                      sbuf231;
   Rte_DE_ALgtSoftMaxReq0                  sbuf232;
   Rte_DE_ALgtReqAttrbArbd0                sbuf233;
   Rte_DE_ALgtMinReq0                      sbuf234;
   Rte_DE_ALgtHardMaxReq0                  sbuf235;
   Rte_DE_RoadInclnRec1                    sbuf236;
   Rte_DE_ReqSts1                          sbuf237;
   Rte_DE_DevErrSts2                       sbuf238;
   Rte_DE_SnsrForLvlSuspPosnVertRe0        sbuf239;
   Rte_DE_SnsrForLvlSuspPosnVertFrnt0      sbuf240;
   Rte_DE_GenQf1                           sbuf241;
   Rte_DE_NoYes1                           sbuf242;
   Rte_DE_NoYes1                           sbuf243;
   Rte_DE_KL30Voltage0                     sbuf244;
   Rte_DE_EngCooltSnsrWdAvl0               sbuf245;
   Rte_DE_BrkFldSnsrWdAvl0                 sbuf246;
   Rte_DE_RscResdSigToVehDynCtrl270        sbuf247;
   Rte_DE_OnOff1                           sbuf248;
   Rte_DE_DevErrSts2                       sbuf249;
   Rte_DE_A33                              sbuf250;
   Rte_DE_AsyBrkEnaAckd0                   sbuf251;
   Rte_DE_AsySftyBrkDlyEstimd0             sbuf252;
   Rte_DE_AsySftyDecelEnadByVehDyn0        sbuf253;
   Rte_DE_AxleSlipRelAct0                  sbuf254;
   Rte_DE_NoYes1                           sbuf255;
   Rte_DE_NoYes1                           sbuf256;
   Rte_DE_NoYes1                           sbuf257;
   Rte_DE_TSts1                            sbuf258;
   Rte_DE_BrkAndAbsWarnIndcnReq0           sbuf259;
   Rte_DE_BrkByWireWarnIndcn0              sbuf260;
   Rte_DE_BrkFricTqTotAtWhlsActRec1        sbuf261;
   Rte_DE_BrkHptcStsSafe0                  sbuf262;
   Rte_DE_BrkLiOnReq0                      sbuf263;
   Rte_DE_BrkMsgForHybWarnReq0             sbuf264;
   Rte_DE_NoYes1                           sbuf265;
   Rte_DE_BrkMsgWarnReq0                   sbuf266;
   Rte_DE_BrkSysWarnIndcnReq0              sbuf267;
   Rte_DE_CtrlSts1                         sbuf268;
   Rte_DE_DispMsgByVehHld1WdDispMsg0       sbuf269;
   Rte_DE_DrvrBrkTqAtWhlsGrdtReqd0         sbuf270;
   Rte_DE_DrvrBrkTqAtWhlsReqdRec1          sbuf271;
   Rte_DE_DstTrvldFromBrkBkp0              sbuf272;
   Rte_DE_InvldVld1                        sbuf273;
   Rte_DE_DynModOfPtReq0                   sbuf274;
   Rte_DE_EmgyBrkLiReq0                    sbuf275;
   Rte_DE_EngRunngReqByBrk0                sbuf276;
   Rte_DE_EpbBtnCtrlSt0                    sbuf277;
   Rte_DE_EpbDrvrDisp1WdDrvrDisp0          sbuf278;
   Rte_DE_EpbLampReq0                      sbuf279;
   Rte_DE_NoYes1                           sbuf280;
   Rte_DE_EscDamprReq0                     sbuf281;
   Rte_DE_EscGearShiftInhbReq0             sbuf282;
   Rte_DE_LatCtrlMod3                      sbuf283;
   Rte_DE_Tq1                              sbuf284;
   Rte_DE_EscSt0                           sbuf285;
   Rte_DE_EscWarnIndcnReq0                 sbuf286;
   Rte_DE_ImobBrkNrSerl0                   sbuf287;
   Rte_DE_IndcnToDrvrPostImpctCtrl0        sbuf288;
   Rte_DE_InhbOfAsySftyDecelByVehDyn0      sbuf289;
   Rte_DE_LampReqByVehHld1WdLampReq0       sbuf290;
   Rte_DE_LimForDecel0                     sbuf291;
   Rte_DE_LimForJerkPosNotExcd0            sbuf292;
   Rte_DE_MsgReqByHillDwnCtrl0             sbuf293;
   Rte_DE_PrpsnTqForBrkRelsToVehDyn0       sbuf294;
   Rte_DE_PtActrReModReq0                  sbuf295;
   Rte_DE_PtTqAtAxleAddReq0                sbuf296;
   Rte_DE_PtTqAtAxleFrntMaxReq0            sbuf297;
   Rte_DE_PtTqAtAxleFrntMinReq0            sbuf298;
   Rte_DE_PtTqAtAxleReMaxReq0              sbuf299;
   Rte_DE_PtTqAtAxleReMinReq0              sbuf300;
   Rte_DE_PtTqAtAxleReMinSlowReq0          sbuf301;
   Rte_DE_NoYes1                           sbuf302;
   Rte_DE_RscResdSigToVehDynCtrl10x        sbuf303;
   Rte_DE_RscResdSigToVehDynCtrl20x        sbuf304;
   Rte_DE_RscResdSigToVehDynCtrl30x        sbuf305;
   Rte_DE_RscResdSigToVehDynCtrl70         sbuf306;
   Rte_DE_RscResdSigToVehDynCtrl80         sbuf307;
   Rte_DE_RscResdSigToVehDynCtrl90         sbuf308;
   Rte_DE_RscResdSigToVehDynCtrl100        sbuf309;
   Rte_DE_RscResdSigToVehDynCtrl110        sbuf310;
   Rte_DE_RscResdSigToVehDynCtrl200        sbuf311;
   Rte_DE_RscResdSigToVehDynCtrl280        sbuf312;
   Rte_DE_RscResdSigToVehDynCtrl290        sbuf313;
   Rte_DE_RscResdSigToVehDynCtrl300        sbuf314;
   Rte_DE_RscResdSigToVehDynCtrl310        sbuf315;
   Rte_DE_RscResdSigToVehDynCtrl320        sbuf316;
   Rte_DE_RscResdSigToVehDynCtrl330        sbuf317;
   Rte_DE_RscResdSigToVehDynCtrl340        sbuf318;
   Rte_DE_RscResdSigToVehDynCtrl350        sbuf319;
   Rte_DE_RscResdSigToVehDynCtrl360        sbuf320;
   Rte_DE_SpdRotlForWhlsAtAxleFrntSafe0    sbuf321;
   Rte_DE_SpdRotlForWhlsAtAxleRe0          sbuf322;
   Rte_DE_StandStillMgrStsForHld1          sbuf323;
   Rte_DE_StandStillMgrStsForPark1         sbuf324;
   Rte_DE_TSts1                            sbuf325;
   Rte_DE_WhlRotCntrFrnt0                  sbuf326;
   Rte_DE_WhlSpdCircumlFrnt0               sbuf327;
   Rte_DE_WhlSpdCircumlRe0                 sbuf328;
   Rte_DE_WhlVAgrFrntRec1                  sbuf329;
   Rte_DE_WhlVAgrReRec1                    sbuf330;
   Rte_DE_YawRateReqdByDrvr0               sbuf331;
   Rte_DE_CtrlSts1                         sbuf332;
   Rte_DE_BrkSysCylPMst0                   sbuf333;
   Rte_DE_PedlFCompCtrlSt0                 sbuf334;
   Rte_DE_BrkBoostVolFlowReq0              sbuf335;
   Rte_DE_WhlBrkPEstimdMax0                sbuf336;
   Rte_DE_PtBrkTqReq0                      sbuf337;
   Rte_DE_NoYes1                           sbuf338;
   Rte_DE_PVac0                            sbuf339;
   Rte_DE_SnsrForLvlWdSplyStRec            sbuf340;
   Rte_DE_SnsrCfg0                         sbuf341;
   Rte_DE_ReqSts1                          sbuf342;
   Rte_DE_CCPFrameResp0                    sbuf343;
   Rte_DE_ChassisCntrForMissCom0           sbuf344;
   Rte_DE_MstCfgIDChassisCAN0              sbuf345;
   Rte_DE_MstCfgIDPropulsionCAN0           sbuf346;
   Rte_DE_PrpsnCntrForMissCom0             sbuf347;
   Rte_DE_VehDynCtrlResdSigToRsc100        sbuf348;
   Rte_DE_VehDynCtrlResdSigToRsc110        sbuf349;
   Rte_DE_VehDynCtrlResdSigToRsc120        sbuf350;
   Rte_DE_VehDynCtrlResdSigToRsc130        sbuf351;
   Rte_DE_VehDynCtrlResdSigToRsc140        sbuf352;
   Rte_DE_VehDynCtrlResdSigToRsc150        sbuf353;
   Rte_DE_VehDynCtrlResdSigToRsc160        sbuf354;
   Rte_DE_BltReqFromVehDyn0                sbuf355;
   Rte_DE_DynCalWhlRd0                     sbuf85;
   Rte_DE_DynCalWhlRdStatLoaded0           sbuf86;
   Rte_DE_DynCalWhlJ0                      sbuf87;
   Rte_DE_DynCalWhlBas0                    sbuf88;
   Rte_DE_DynCalVehMUnsprung0              sbuf89;
   Rte_DE_DynCalVehMSprung0                sbuf90;
   Rte_DE_DynCalTrkWidthRe0                sbuf91;
   Rte_DE_DynCalTrkWidthFrnt0              sbuf92;
   Rte_DE_DynCalTireRelaxationLen0         sbuf93;
   Rte_DE_DynCalTireLgtStfnRe0             sbuf94;
   Rte_DE_DynCalTireLgtStfnFrnt0           sbuf95;
   Rte_DE_DynCalSteerRat0                  sbuf96;
   Rte_DE_rt_Array_DynCalSteerColRatTbl0_4 sbuf97;
   Rte_DE_rt_Array_DynCalSteerColAgTbl0_4  sbuf98;
   Rte_DE_DynCalRollStfnRe0                sbuf99;
} Rte_TDB_RTE_PostASW_x2;

typedef struct {
   Rte_DE_VehCfgPrmDT                      rbuf0;
   Rte_DE_DynCalWhlRd0                     sbuf1;
   Rte_DE_DynCalTireLgtStfnRe0             sbuf10;
   Rte_DE_DynCalTireLgtStfnFrnt0           sbuf11;
   Rte_DE_DynCalSteerRat0                  sbuf12;
   Rte_DE_rt_Array_DynCalSteerColRatTbl0_4 sbuf13;
   Rte_DE_rt_Array_DynCalSteerColAgTbl0_4  sbuf14;
   Rte_DE_DynCalRollStfnRe0                sbuf15;
   Rte_DE_DynCalRollStfnFrnt0              sbuf16;
   Rte_DE_DynCalRollSteerCoeffRe0          sbuf17;
   Rte_DE_DynCalRollSteerCoeffFrnt0        sbuf18;
   Rte_DE_DynCalRollSprgCoeff0             sbuf19;
   Rte_DE_DynCalWhlRdStatLoaded0           sbuf2;
   Rte_DE_DynCalRollDampgCoeff0            sbuf20;
   Rte_DE_DynCalRollCenterHeiRe0           sbuf21;
   Rte_DE_DynCalRollCenterHeiFrnt0         sbuf22;
   Rte_DE_DynCalRollAgGrdt0                sbuf23;
   Rte_DE_DynCalRollACoeff0                sbuf24;
   Rte_DE_DynCalReVoltToMtrCnvnFac0        sbuf25;
   Rte_DE_DynCalReRiRbdU0                  sbuf26;
   Rte_DE_DynCalPitchDecelGrdt0            sbuf27;
   Rte_DE_DynCalPitchAGrdt0                sbuf28;
   Rte_DE_DynCalLgtSlipCmpConRe0           sbuf29;
   Rte_DE_DynCalWhlJ0                      sbuf3;
   Rte_DE_DynCalLgtSlipCmpConFrnt0         sbuf30;
   Rte_DE_DynCalLatLoadShiftGrdtRe0        sbuf31;
   Rte_DE_DynCalLatLoadShiftGrdtFrnt0      sbuf32;
   Rte_DE_DynCalHeiCog0                    sbuf33;
   Rte_DE_DynCalFrntVoltToMtrCnvnFac0      sbuf34;
   Rte_DE_DynCalFrntRiRbdU0                sbuf35;
   Rte_DE_DynCalFrntAr0                    sbuf36;
   Rte_DE_DynCalDrgHei0                    sbuf37;
   Rte_DE_DynCalDrgCoeff0                  sbuf38;
   Rte_DE_DynCalDistRollAxleToCog0         sbuf39;
   Rte_DE_DynCalWhlBas0                    sbuf4;
   Rte_DE_DynCalDistCogToRe0               sbuf40;
   Rte_DE_DynCalDistCogToFrnt0             sbuf41;
   Rte_DE_DynCalCurbWght0                  sbuf42;
   Rte_DE_DynCalCornrgStfnRe0              sbuf43;
   Rte_DE_DynCalCornrgStfnFrnt0            sbuf44;
   Rte_DE_DynCalCornrgComplRe0             sbuf45;
   Rte_DE_DynCalCornrgComplFrnt0           sbuf46;
   Rte_DE_DynCalBodyYawRollJ0              sbuf47;
   Rte_DE_DynCalBodyYawJ0                  sbuf48;
   Rte_DE_DynCalBodyRollJ0                 sbuf49;
   Rte_DE_DynCalVehMUnsprung0              sbuf5;
   Rte_DE_CarCfgVehSpdMax0                 sbuf50;
   Rte_DE_CarCfgPrmiTPMSSysDT              sbuf51;
   Rte_DE_CarCfgPrmVehTypDT                sbuf52;
   Rte_DE_TrsmDrvLine                      sbuf53;
   Rte_DE_CarCfgPrmTowBarDT                sbuf54;
   Rte_DE_CarCfgPrmTireSizeDT              sbuf55;
   Rte_DE_PropulsionTyp                    sbuf56;
   Rte_DE_CarCfgPrmLvlSnsr0                sbuf57;
   Rte_DE_CarCfgPrmGnssRxr0                sbuf58;
   Rte_DE_CarCfgPrmGbxTypDT                sbuf59;
   Rte_DE_DynCalVehMSprung0                sbuf6;
   Rte_DE_CarCfgPrmFuTypDT                 sbuf60;
   Rte_DE_CarCfgPrmEngTypDT                sbuf61;
   Rte_DE_CarCfgPrmContnslyCtrldDampgDT    sbuf62;
   Rte_DE_CarCfgPrmAirSuspDT               sbuf63;
   Rte_DE_NoYes1                           sbuf64;
   Rte_DE_DynCalTrkWidthRe0                sbuf7;
   Rte_DE_DynCalTrkWidthFrnt0              sbuf8;
   Rte_DE_DynCalTireRelaxationLen0         sbuf9;
} Rte_TDB_RTE_TaskInit;

typedef union {
   Rte_TDB_RTE_PostASW_x2 _RTE_PostASW_x2;
   Rte_TDB_RTE_TaskInit   _RTE_TaskInit;
} Rte_ISA_4;

typedef struct {
   Rte_ISA_4 isa_4;
} Rte_ImplicitBufsType;

#endif /* !RTE_DATA_HANDLE_TYPE_H */
