

/*                                                                                                                     
********************************************************************************************************************** 
*                                                                                                                      
* COPYRIGHT RESERVED, 2010 Robert Bosch GmbH. All rights reserved.                                                     
* The reproduction, distribution and utilization of this document as well as the communication of its contents to      
* others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.       
* All rights reserved in the event of the grant of a patent, utility model or design.                                  
*                                                                                                                      
********************************************************************************************************************** 
*/                                                                                                                     

/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/


#ifndef DEM_CFG_EVENTID_H
#define DEM_CFG_EVENTID_H


#define DEM_EVENTID_INVALID                                          0
#define DEM_EVENTID_COUNT         602
#define DEM_EVENTID_ARRAYLENGTH   (DEM_EVENTID_COUNT+1)

#define DemConf_DemEventParameter_AssertionFailed                    1
#define DemConf_DemEventParameter_RBuCSupplyError                    2
#define DemConf_DemEventParameter_RBHWBISTError                      3
#define DemConf_DemEventParameter_RBFlashFailure                     4
#define DemConf_DemEventParameter_RBuCSafetyFault                    5
#define DemConf_DemEventParameter_RBuCSafetyLogicFault               6
#define DemConf_DemEventParameter_RBCPUException                     7
#define DemConf_DemEventParameter_RBSYS_StackOverUnderFlow           8
#define DemConf_DemEventParameter_RBSYS_SYSErrorHook                 9
#define DemConf_DemEventParameter_RBSYS_OSErrorHook                  10
#define DemConf_DemEventParameter_RBSYS_TaskOverRun                  11
#define DemConf_DemEventParameter_RBOSTaskSchemeError                12
#define DemConf_DemEventParameter_RBDmaTransferError                 13
#define DemConf_DemEventParameter_RbmicAsicOscillatorError           14
#define DemConf_DemEventParameter_RB_UnsupportedHW                   15
#define DemConf_DemEventParameter_RBSupplyASICInitFailure            16
#define DemConf_DemEventParameter_RBSUPPLYVPREU5VOutOfRange          17
#define DemConf_DemEventParameter_RBSUPPLYIREFOutOfRange             18
#define DemConf_DemEventParameter_RBSUPPLY_U5VTestFailure            19
#define DemConf_DemEventParameter_RBSUPPLY_U5VTestTimeout            20
#define DemConf_DemEventParameter_RBSUPPLY_U5VOutOfRange             21
#define DemConf_DemEventParameter_RbfslEcuErrpinCounterTestFails     22
#define DemConf_DemEventParameter_RbfslEcuWdStatusContinuousError    23
#define DemConf_DemEventParameter_RbfslEcuEnableElLowFails           24
#define DemConf_DemEventParameter_RbfslEcuEnableElHighFails          25
#define DemConf_DemEventParameter_RbfslEcuEClockTestFails            26
#define DemConf_DemEventParameter_RbfslEcuWrongBistCmdTestFails      27
#define DemConf_DemEventParameter_RbfslEcuFastWdTestFails            28
#define DemConf_DemEventParameter_RbfslEcuBistFailureCtrTestFails    29
#define DemConf_DemEventParameter_RbfslEcuEnContinuousError          30
#define DemConf_DemEventParameter_RbfslEcuWdStartuptestFails         31
#define DemConf_DemEventParameter_RbfslEcuEnableHyHighFails          32
#define DemConf_DemEventParameter_RbfslEcuEnableHyLowFails           33
#define DemConf_DemEventParameter_RbfslEcuVrViaSpiFails              34
#define DemConf_DemEventParameter_RbfslEcuVrOnWhileWdTimeout         35
#define DemConf_DemEventParameter_RbfslSafetySwitchTestFails         36
#define DemConf_DemEventParameter_RBVR_LeakageDetectionUnitDefective  37
#define DemConf_DemEventParameter_RBGTM_RefFrequencyError            38
#define DemConf_DemEventParameter_RbmicAsicClkInError                39
#define DemConf_DemEventParameter_RbmicAsicInitTestError             40
#define DemConf_DemEventParameter_RbmicSpiTransferError              41
#define DemConf_DemEventParameter_RbmicUnsupportedAsicRevisionId     42
#define DemConf_DemEventParameter_RbWdhAsicWdErrorCntStuck           43
#define DemConf_DemEventParameter_RbWdhAsicWdErrorCntLimit           44
#define DemConf_DemEventParameter_RbWdhAsicWdCmdMissing              45
#define DemConf_DemEventParameter_RBEcuBandgap                       46
#define DemConf_DemEventParameter_RBAdcSelftestI3P                   47
#define DemConf_DemEventParameter_RBAdcPinTest                       48
#define DemConf_DemEventParameter_RBAdcSelftestC5P                   49
#define DemConf_DemEventParameter_RBWssRrWssModeFail                 50
#define DemConf_DemEventParameter_RBWssFrWssModeFail                 51
#define DemConf_DemEventParameter_RBWssRlWssModeFail                 52
#define DemConf_DemEventParameter_RBwssFlWssModeFail                 53
#define DemConf_DemEventParameter_MoCMonEnableLineViolation          54
#define DemConf_DemEventParameter_PbcShadowMemError                  55
#define DemConf_DemEventParameter_RbmicApbAsicInitTestError          56
#define DemConf_DemEventParameter_RbmicApbTransferError              57
#define DemConf_DemEventParameter_RbmicApbSpiModeError               58
#define DemConf_DemEventParameter_RbmicApbAsicResetError             59
#define DemConf_DemEventParameter_RbmicApbUnsupportedAsicRevisionId  60
#define DemConf_DemEventParameter_STM_AswSystemTimeOut               61
#define DemConf_DemEventParameter_RBBrakeFluidLevelTooHigh           62
#define DemConf_DemEventParameter_RBBrakeFluidEmpty                  63
#define DemConf_DemEventParameter_AcmVs_LowVacHBCOff                 64
#define DemConf_DemEventParameter_AcmVs_BoosterLowVac                65
#define DemConf_DemEventParameter_AcmBtm_OverheatWarningDeactivated  66
#define DemConf_DemEventParameter_AcmBtm_OverheatDuringActiveBraking  67
#define DemConf_DemEventParameter_Dtc407768                          68
#define DemConf_DemEventParameter_Dtc407864                          69
#define DemConf_DemEventParameter_Dtc507593                          70
#define DemConf_DemEventParameter_Dtc507693                          71
#define DemConf_DemEventParameter_Dtc507908                          72
#define DemConf_DemEventParameter_Dtc507968                          73
#define DemConf_DemEventParameter_Dtc507993                          74
#define DemConf_DemEventParameter_Dtc512486                          75
#define DemConf_DemEventParameter_Dtc5a0416                          76
#define DemConf_DemEventParameter_Dtc5a0417                          77
#define DemConf_DemEventParameter_Dtc5a042a                          78
#define DemConf_DemEventParameter_Dtc5a042f                          79
#define DemConf_DemEventParameter_Dtc5a0481                          80
#define DemConf_DemEventParameter_Dtc5a0616                          81
#define DemConf_DemEventParameter_Dtc5a0617                          82
#define DemConf_DemEventParameter_Dtc5a062a                          83
#define DemConf_DemEventParameter_Dtc5a062f                          84
#define DemConf_DemEventParameter_Dtc5a0681                          85
#define DemConf_DemEventParameter_Dtc904154                          86
#define DemConf_DemEventParameter_Dtc911193                          87
#define DemConf_DemEventParameter_Dtce30051                          88
#define DemConf_DemEventParameter_Dtce30054                          89
#define DemConf_DemEventParameter_Dtce30055                          90
#define DemConf_DemEventParameter_Dtce30056                          91
#define DemConf_DemEventParameter_Dtce40057                          92
#define DemConf_DemEventParameter_Dtcec4981                          93
#define DemConf_DemEventParameter_Dtcec4a81                          94
#define DemConf_DemEventParameter_Dtcec4b81                          95
#define DemConf_DemEventParameter_Dtcec4c81                          96
#define DemConf_DemEventParameter_Dtcec4d81                          97
#define DemConf_DemEventParameter_Dtcec4e81                          98
#define DemConf_DemEventParameter_Dtcecd981                          99
#define DemConf_DemEventParameter_Dtcecda81                          100
#define DemConf_DemEventParameter_Dtcecdb81                          101
#define DemConf_DemEventParameter_Dtcecdc81                          102
#define DemConf_DemEventParameter_Dtcecdd81                          103
#define DemConf_DemEventParameter_Dtced3d49                          104
#define DemConf_DemEventParameter_Dtced5383                          105
#define DemConf_DemEventParameter_Dtced7783                          106
#define DemConf_DemEventParameter_Dtced7792                          107
#define DemConf_DemEventParameter_Dtced7849                          108
#define DemConf_DemEventParameter_Dtcf00046                          109
#define DemConf_DemEventParameter_Dtcf00362                          110
#define DemConf_DemEventParameter_RBCoolSnsShortUbatt                111
#define DemConf_DemEventParameter_CCC_MissingCalibration             112
#define DemConf_DemEventParameter_CCC_InvalidConfiguration           113
#define DemConf_DemEventParameter_CarConfiguration_NotConfigured     114
#define DemConf_DemEventParameter_CCC_incomplete_vehicle_configuration_data  115
#define DemConf_DemEventParameter_CCC_Invalid_local_configuration_data  116
#define DemConf_DemEventParameter_CCC_Not_programmed                 117
#define DemConf_DemEventParameter_Abs_ContControl                    118
#define DemConf_DemEventParameter_Vdc_ContControl                    119
#define DemConf_DemEventParameter_Abs_EmergencyBrake                 120
#define DemConf_DemEventParameter_VDCRefnotInitInTime                121
#define DemConf_DemEventParameter_Abs_FBC1                           122
#define DemConf_DemEventParameter_Frame_configuration_error          123
#define DemConf_DemEventParameter_RBSUPPLYESP_UBVrSupplyLine         124
#define DemConf_DemEventParameter_RBHydraulicHardUndervoltage        125
#define DemConf_DemEventParameter_RbfslFailsafeLogicTestTimeout      126
#define DemConf_DemEventParameter_RbfslSafetySwitchTestTimeout       127
#define DemConf_DemEventParameter_RBIISSMI7InternalHWTestTimeout     128
#define DemConf_DemEventParameter_RBIISSMI7WrongHWRevision           129
#define DemConf_DemEventParameter_RBIISSMI7SpiTransError             130
#define DemConf_DemEventParameter_RBIISSMI7SensorCRCCheck            131
#define DemConf_DemEventParameter_RBIISSMI7GSBitsMissed              132
#define DemConf_DemEventParameter_RBIISSMI7ConfigurationError        133
#define DemConf_DemEventParameter_RBIISEEPromError                   134
#define DemConf_DemEventParameter_RBIISOEMCalibrationError           135
#define DemConf_DemEventParameter_TCSRefnotInitInTime                136
#define DemConf_DemEventParameter_NET_Undervoltage                   137
#define DemConf_DemEventParameter_NET_Overvoltage                    138
#define DemConf_DemEventParameter_NET_ParityErrorFlxrCtrl0           139
#define DemConf_DemEventParameter_CUBAS_PDUR_E_PDU_Instance_Lost     140
#define DemConf_DemEventParameter_CUBAS_CAN_E_HW_ERROR               141
#define DemConf_DemEventParameter_CUBAS_CAN_E_Timeout                142
#define DemConf_DemEventParameter_CANNM_E_NETWORK_TIMEOUT            143
#define DemConf_DemEventParameter_CANNM_E_CANIF_TRANSMIT_ERROR       144
#define DemConf_DemEventParameter_CANNM_E_INIT_FAILED                145
#define DemConf_DemEventParameter_PDUR_E_PDU_INSTANCE_LOST           146
#define DemConf_DemEventParameter_CANIF_E_INVALID_TXPDUID            147
#define DemConf_DemEventParameter_CAN_E_HW_ERROR                     148
#define DemConf_DemEventParameter_PDUR_E_INIT_FAILED                 149
#define DemConf_DemEventParameter_CAN_E_OVERFLOW                     150
#define DemConf_DemEventParameter_CANIF_E_STOPPED                    151
#define DemConf_DemEventParameter_CAN_E_TIMEOUT                      152
#define DemConf_DemEventParameter_COMM_E_NET_START_IND_CHANNEL_0     153
#define DemConf_DemEventParameter_COMM_E_NET_START_IND_CHANNEL_1     154
#define DemConf_DemEventParameter_FRIF_DEM_JLE_NOT_SYNC_ID_0         155
#define DemConf_DemEventParameter_LIN_E_TIMEOUT                      156
#define DemConf_DemEventParameter_NET_NoSyncFlxrCtrl0                157
#define DemConf_DemEventParameter_PbcFaultState_5                    158
#define DemConf_DemEventParameter_PbcFaultState_3                    159
#define DemConf_DemEventParameter_PbcFaultState_4                    160
#define DemConf_DemEventParameter_PbcFaultState_2                    161
#define DemConf_DemEventParameter_PbcFaultState_1                    162
#define DemConf_DemEventParameter_DET_ReportError                    163
#define DemConf_DemEventParameter_PbcFaultState_21                   164
#define DemConf_DemEventParameter_PbcFaultState_20                   165
#define DemConf_DemEventParameter_PbcFaultState_19                   166
#define DemConf_DemEventParameter_PbcFaultState_15                   167
#define DemConf_DemEventParameter_PbcFaultState_22                   168
#define DemConf_DemEventParameter_PbcFaultState_37                   169
#define DemConf_DemEventParameter_PbcFaultState_26                   170
#define DemConf_DemEventParameter_PbcFaultState_35                   171
#define DemConf_DemEventParameter_PbcFaultState_9                    172
#define DemConf_DemEventParameter_PbcFaultState_30                   173
#define DemConf_DemEventParameter_PbcFaultState_24                   174
#define DemConf_DemEventParameter_PbcFaultState_36                   175
#define DemConf_DemEventParameter_PbcFaultState_29                   176
#define DemConf_DemEventParameter_PbcFaultState_27                   177
#define DemConf_DemEventParameter_PbcFaultState_33                   178
#define DemConf_DemEventParameter_PbcFaultState_25                   179
#define DemConf_DemEventParameter_PbcFaultState_39                   180
#define DemConf_DemEventParameter_PbcFaultState_38                   181
#define DemConf_DemEventParameter_PbcFaultState_32                   182
#define DemConf_DemEventParameter_PbcFaultState_31                   183
#define DemConf_DemEventParameter_PbcFaultState_34                   184
#define DemConf_DemEventParameter_PbcFaultState_23                   185
#define DemConf_DemEventParameter_PbcFaultState_28                   186
#define DemConf_DemEventParameter_PbcFaultState_8                    187
#define DemConf_DemEventParameter_PbcFaultState_18                   188
#define DemConf_DemEventParameter_PbcFaultState_17                   189
#define DemConf_DemEventParameter_PbcFaultState_16                   190
#define DemConf_DemEventParameter_PbcFaultState_10                   191
#define DemConf_DemEventParameter_PbcFaultState_13                   192
#define DemConf_DemEventParameter_PbcFaultState_11                   193
#define DemConf_DemEventParameter_PbcFaultState_12                   194
#define DemConf_DemEventParameter_PbcFaultState_14                   195
#define DemConf_DemEventParameter_PbcFaultState_0                    196
#define DemConf_DemEventParameter_PbcFaultState_7                    197
#define DemConf_DemEventParameter_PbcFaultState_6                    198
#define DemConf_DemEventParameter_RBPressSensFLLineLo                199
#define DemConf_DemEventParameter_RBPressSensFLLineHi                200
#define DemConf_DemEventParameter_RBPressSensFRLine                  201
#define DemConf_DemEventParameter_RBPressSensFRLineLo                202
#define DemConf_DemEventParameter_RBPressSensFRLineHi                203
#define DemConf_DemEventParameter_AcmPs_TestpulseFR                  204
#define DemConf_DemEventParameter_AcmPs_OffsetFR                     205
#define DemConf_DemEventParameter_RBPressSensMC1LineLo               206
#define DemConf_DemEventParameter_RBPressSensMC1LineHi               207
#define DemConf_DemEventParameter_AcmPs_TestpulseMC1                 208
#define DemConf_DemEventParameter_AcmPs_OffsetMC1                    209
#define DemConf_DemEventParameter_AcmPs_TestpulseRL                  210
#define DemConf_DemEventParameter_AcmPs_OffsetRL                     211
#define DemConf_DemEventParameter_RBRFPPumpMotorTestFailure          212
#define DemConf_DemEventParameter_RBSUPPLYESP_UBMrSupplyLine         213
#define DemConf_DemEventParameter_RBRFPSupplyCheckLogicTestFailure   214
#define DemConf_DemEventParameter_RBHydraulicUndervoltage            215
#define DemConf_DemEventParameter_RBOvervoltage                      216
#define DemConf_DemEventParameter_RBRFPAdcConnectTestFailure         217
#define DemConf_DemEventParameter_RBRFPMraUcTestFailure              218
#define DemConf_DemEventParameter_RBRFPFreewheelingPathTestFailure   219
#define DemConf_DemEventParameter_RBRFPMrsNegTestFailure             220
#define DemConf_DemEventParameter_RBRFPMrgTestFailure                221
#define DemConf_DemEventParameter_RBRFPLoadDumpTestFailure           222
#define DemConf_DemEventParameter_RBRFPInverseMotorActuationTestFailure  223
#define DemConf_DemEventParameter_RBRFPCccModulatorTestFailure       224
#define DemConf_DemEventParameter_RBRFPAnsModulatorTestFailure       225
#define DemConf_DemEventParameter_RBRFPMrsTestFailure                226
#define DemConf_DemEventParameter_RBRFPFwsTestFailure                227
#define DemConf_DemEventParameter_RBRFPMrdFailure                    228
#define DemConf_DemEventParameter_RBRFPMrsNegFailure                 229
#define DemConf_DemEventParameter_RBRFPMrdMinusMrsSlowFailure        230
#define DemConf_DemEventParameter_RBRFPMrdMinusMrsFastFailure        231
#define DemConf_DemEventParameter_RBRFPImotOffsetFailure             232
#define DemConf_DemEventParameter_RBRFPUmotOffsetFailure             233
#define DemConf_DemEventParameter_AcmHyd_ReturnPumpWeak              234
#define DemConf_DemEventParameter_SMM_OneRequestsInit                235
#define DemConf_DemEventParameter_ScmSkidDetected                    236
#define DemConf_DemEventParameter_RBVacSent1LineHigh                 237
#define DemConf_DemEventParameter_RBVacSent1LineLow                  238
#define DemConf_DemEventParameter_RBVacSent1Transmission             239
#define DemConf_DemEventParameter_RBVacSent1SensorInternal           240
#define DemConf_DemEventParameter_RBVacSupplyUndervolt               241
#define DemConf_DemEventParameter_RBVacSupply                        242
#define DemConf_DemEventParameter_RBVacFrontChamberLine              243
#define DemConf_DemEventParameter_RBVacFrontChamberLineLo            244
#define DemConf_DemEventParameter_RBVacFrontChamberLineHi            245
#define DemConf_DemEventParameter_AcmVs_SignalPlaus                  246
#define DemConf_DemEventParameter_RBVR_Short2GND_Continuous          247
#define DemConf_DemEventParameter_RBVR_Short2GNDMonitoringTimeOutOccurred  248
#define DemConf_DemEventParameter_RBVR_HighOhmicShort2GND_Continuous  249
#define DemConf_DemEventParameter_RBVR_VRGOnSpiFails_Continuous      250
#define DemConf_DemEventParameter_RBVR_VROnFails_Continuous          251
#define DemConf_DemEventParameter_RbfslVrOnFails                     252
#define DemConf_DemEventParameter_RbfslVrStuck                       253
#define DemConf_DemEventParameter_RBVR_VROffFails_Continuous         254
#define DemConf_DemEventParameter_RBWssTestSystemICFailure           255
#define DemConf_DemEventParameter_Wss_MonVDiff_Gen                   256
#define DemConf_DemEventParameter_RBAPBMOTAsicAdcCounterFailure      257
#define DemConf_DemEventParameter_RBAPBMOTSupplyPlausibility         258
#define DemConf_DemEventParameter_RBAPBMOT_EnLeftAndRightLowContinuousError  259
#define DemConf_DemEventParameter_RBAPBMOT_EnRightLowContinuousError  260
#define DemConf_DemEventParameter_RBAPBMOT_EnLeftLowContinuousError  261
#define DemConf_DemEventParameter_RBAPBMOT_EnLeftHighFails           262
#define DemConf_DemEventParameter_RBAPBMOT_EnLeftLowFails            263
#define DemConf_DemEventParameter_RBAPBMOT_EnRightHighFails          264
#define DemConf_DemEventParameter_RBAPBMOT_EnRightLowFails           265
#define DemConf_DemEventParameter_RBApbButtonSupplyUndervolt         266
#define DemConf_DemEventParameter_RBApbButtonInternal5VSupply        267
#define DemConf_DemEventParameter_RBApbButtonConfiguration           268
#define DemConf_DemEventParameter_RBApbButtonLine                    269
#define DemConf_DemEventParameter_ApbButtonAlwaysPushedOrPulled      270
#define DemConf_DemEventParameter_AcmLtm_HydUnitWornCco              271
#define DemConf_DemEventParameter_AcmLtm_HydUnitWornVlc              272
#define DemConf_DemEventParameter_AcmLtm_HydUnitWornAvh              273
#define DemConf_DemEventParameter_AcmLtm_HydUnitWornCdd              274
#define DemConf_DemEventParameter_AcmLtm_HydUnitWornHdc              275
#define DemConf_DemEventParameter_RBIISSMI7GeneralAsFault            276
#define DemConf_DemEventParameter_RBIISSMI7GeneralYrsFault           277
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID1_DlcError         278
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID1_Timeout          279
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID1_ChksmError       280
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID1_AlvCntError      281
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID7_DlcError         282
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID7_Timeout          283
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID7_ChksmError       284
#define DemConf_DemEventParameter_ComScl_MMx_TX_ID7_AlvCntError      285
#define DemConf_DemEventParameter_CANSM_E_BUSOFF_NETWORK_0           286
#define DemConf_DemEventParameter_CANSM_E_BUSOFF_NETWORK_1           287
#define DemConf_DemEventParameter_OvervoltageReplacementFault_Net0   288
#define DemConf_DemEventParameter_UndervoltageReplacementFault_Net0  289
#define DemConf_DemEventParameter_Scl_E2E_SteerWhlSnsr_TO            290
#define DemConf_DemEventParameter_Scl_E2E_SteerWhlSnsr_CHK           291
#define DemConf_DemEventParameter_Scl_E2E_SteerWhlSnsr_AC            292
#define DemConf_DemEventParameter_Sas_Uncert                         293
#define DemConf_DemEventParameter_RBVLV_MV0_ValveCoilPathInterruptionFailure  294
#define DemConf_DemEventParameter_RBVLV_MV0_GeneralValveDriverFailure  295
#define DemConf_DemEventParameter_RBVLV_MV0_ValveDriverGateQxFailure  296
#define DemConf_DemEventParameter_RBVLV_MV0_SVDTFailure              297
#define DemConf_DemEventParameter_RBVLV_MV0_VARTFailure              298
#define DemConf_DemEventParameter_RBVLV_MV0_ValveCoilResistanceOutOfRangeFailure  299
#define DemConf_DemEventParameter_RBVLV_MV0_ValveDriverLBISTFailure  300
#define DemConf_DemEventParameter_RBVLV_MV1A_ValveCoilPathInterruptionFailure  301
#define DemConf_DemEventParameter_RBVLV_MV1A_GeneralValveDriverFailure  302
#define DemConf_DemEventParameter_RBVLV_MV1A_ValveDriverGateQxFailure  303
#define DemConf_DemEventParameter_RBVLV_MV1A_SVDTFailure             304
#define DemConf_DemEventParameter_RBVLV_MV1A_VARTFailure             305
#define DemConf_DemEventParameter_RBVLV_MV1A_ValveCoilResistanceOutOfRangeFailure  306
#define DemConf_DemEventParameter_RBVLV_MV1A_ValveDriverLBISTFailure  307
#define DemConf_DemEventParameter_RBVLV_MV1B_ValveCoilPathInterruptionFailure  308
#define DemConf_DemEventParameter_RBVLV_MV1B_GeneralValveDriverFailure  309
#define DemConf_DemEventParameter_RBVLV_MV1B_ValveDriverGateQxFailure  310
#define DemConf_DemEventParameter_RBVLV_MV1B_SVDTFailure             311
#define DemConf_DemEventParameter_RBVLV_MV1B_VARTFailure             312
#define DemConf_DemEventParameter_RBVLV_MV1B_ValveCoilResistanceOutOfRangeFailure  313
#define DemConf_DemEventParameter_RBVLV_MV1B_ValveDriverLBISTFailure  314
#define DemConf_DemEventParameter_RBVLV_MV2A_ValveCoilPathInterruptionFailure  315
#define DemConf_DemEventParameter_RBVLV_MV2A_GeneralValveDriverFailure  316
#define DemConf_DemEventParameter_RBVLV_MV2A_ValveDriverGateQxFailure  317
#define DemConf_DemEventParameter_RBVLV_MV2A_SVDTFailure             318
#define DemConf_DemEventParameter_RBVLV_MV2A_VARTFailure             319
#define DemConf_DemEventParameter_RBVLV_MV2A_ValveCoilResistanceOutOfRangeFailure  320
#define DemConf_DemEventParameter_RBVLV_MV2A_ValveDriverLBISTFailure  321
#define DemConf_DemEventParameter_RBVLV_MV2B_ValveCoilPathInterruptionFailure  322
#define DemConf_DemEventParameter_RBVLV_MV2B_GeneralValveDriverFailure  323
#define DemConf_DemEventParameter_RBVLV_MV2B_ValveDriverGateQxFailure  324
#define DemConf_DemEventParameter_RBVLV_MV2B_SVDTFailure             325
#define DemConf_DemEventParameter_RBVLV_MV2B_VARTFailure             326
#define DemConf_DemEventParameter_RBVLV_MV2B_ValveCoilResistanceOutOfRangeFailure  327
#define DemConf_DemEventParameter_RBVLV_MV2B_ValveDriverLBISTFailure  328
#define DemConf_DemEventParameter_RBVLV_MV3A_ValveCoilPathInterruptionFailure  329
#define DemConf_DemEventParameter_RBVLV_MV3A_GeneralValveDriverFailure  330
#define DemConf_DemEventParameter_RBVLV_MV3A_ValveDriverGateQxFailure  331
#define DemConf_DemEventParameter_RBVLV_MV3A_SVDTFailure             332
#define DemConf_DemEventParameter_RBVLV_MV3A_VARTFailure             333
#define DemConf_DemEventParameter_RBVLV_MV3A_ValveCoilResistanceOutOfRangeFailure  334
#define DemConf_DemEventParameter_RBVLV_MV3A_ValveDriverLBISTFailure  335
#define DemConf_DemEventParameter_RBVLV_MV3B_ValveCoilPathInterruptionFailure  336
#define DemConf_DemEventParameter_RBVLV_MV3B_GeneralValveDriverFailure  337
#define DemConf_DemEventParameter_RBVLV_MV3B_ValveDriverGateQxFailure  338
#define DemConf_DemEventParameter_RBVLV_MV3B_SVDTFailure             339
#define DemConf_DemEventParameter_RBVLV_MV3B_VARTFailure             340
#define DemConf_DemEventParameter_RBVLV_MV3B_ValveCoilResistanceOutOfRangeFailure  341
#define DemConf_DemEventParameter_RBVLV_MV3B_ValveDriverLBISTFailure  342
#define DemConf_DemEventParameter_RBVLV_MV4A_ValveCoilPathInterruptionFailure  343
#define DemConf_DemEventParameter_RBVLV_MV4A_GeneralValveDriverFailure  344
#define DemConf_DemEventParameter_RBVLV_MV4A_ValveDriverGateQxFailure  345
#define DemConf_DemEventParameter_RBVLV_MV4A_SVDTFailure             346
#define DemConf_DemEventParameter_RBVLV_MV4A_VARTFailure             347
#define DemConf_DemEventParameter_RBVLV_MV4A_ValveCoilResistanceOutOfRangeFailure  348
#define DemConf_DemEventParameter_RBVLV_MV4A_ValveDriverLBISTFailure  349
#define DemConf_DemEventParameter_RBVLV_MV4B_ValveCoilPathInterruptionFailure  350
#define DemConf_DemEventParameter_RBVLV_MV4B_GeneralValveDriverFailure  351
#define DemConf_DemEventParameter_RBVLV_MV4B_ValveDriverGateQxFailure  352
#define DemConf_DemEventParameter_RBVLV_MV4B_SVDTFailure             353
#define DemConf_DemEventParameter_RBVLV_MV4B_VARTFailure             354
#define DemConf_DemEventParameter_RBVLV_MV4B_ValveCoilResistanceOutOfRangeFailure  355
#define DemConf_DemEventParameter_RBVLV_MV4B_ValveDriverLBISTFailure  356
#define DemConf_DemEventParameter_RBVLV_MV5_ValveCoilPathInterruptionFailure  357
#define DemConf_DemEventParameter_RBVLV_MV5_GeneralValveDriverFailure  358
#define DemConf_DemEventParameter_RBVLV_MV5_ValveDriverGateQxFailure  359
#define DemConf_DemEventParameter_RBVLV_MV5_SVDTFailure              360
#define DemConf_DemEventParameter_RBVLV_MV5_VARTFailure              361
#define DemConf_DemEventParameter_RBVLV_MV5_ValveCoilResistanceOutOfRangeFailure  362
#define DemConf_DemEventParameter_RBVLV_MV5_ValveDriverLBISTFailure  363
#define DemConf_DemEventParameter_RBVLV_MV5B_ValveCoilPathInterruptionFailure  364
#define DemConf_DemEventParameter_RBVLV_MV5B_GeneralValveDriverFailure  365
#define DemConf_DemEventParameter_RBVLV_MV5B_ValveDriverGateQxFailure  366
#define DemConf_DemEventParameter_RBVLV_MV5B_SVDTFailure             367
#define DemConf_DemEventParameter_RBVLV_MV5B_VARTFailure             368
#define DemConf_DemEventParameter_RBVLV_MV5B_ValveCoilResistanceOutOfRangeFailure  369
#define DemConf_DemEventParameter_RBVLV_MV5B_ValveDriverLBISTFailure  370
#define DemConf_DemEventParameter_RBVLV_MV6_ValveCoilPathInterruptionFailure  371
#define DemConf_DemEventParameter_RBVLV_MV6_GeneralValveDriverFailure  372
#define DemConf_DemEventParameter_RBVLV_MV6_ValveDriverGateQxFailure  373
#define DemConf_DemEventParameter_RBVLV_MV6_SVDTFailure              374
#define DemConf_DemEventParameter_RBVLV_MV6_ValveCoilResistanceOutOfRangeFailure  375
#define DemConf_DemEventParameter_RBVLV_MV6_VARTFailure              376
#define DemConf_DemEventParameter_RBVLV_MV6_ValveDriverLBISTFailure  377
#define DemConf_DemEventParameter_RBVLV_MV7_ValveCoilPathInterruptionFailure  378
#define DemConf_DemEventParameter_RBVLV_MV7_GeneralValveDriverFailure  379
#define DemConf_DemEventParameter_RBVLV_MV7_ValveDriverGateQxFailure  380
#define DemConf_DemEventParameter_RBVLV_MV7_SVDTFailure              381
#define DemConf_DemEventParameter_RBVLV_MV7_VARTFailure              382
#define DemConf_DemEventParameter_RBVLV_MV7_ValveCoilResistanceOutOfRangeFailure  383
#define DemConf_DemEventParameter_RBVLV_MV7_ValveDriverLBISTFailure  384
#define DemConf_DemEventParameter_RBVLV_MV8_ValveCoilPathInterruptionFailure  385
#define DemConf_DemEventParameter_RBVLV_MV8_GeneralValveDriverFailure  386
#define DemConf_DemEventParameter_RBVLV_MV8_ValveDriverGateQxFailure  387
#define DemConf_DemEventParameter_RBVLV_MV8_SVDTFailure              388
#define DemConf_DemEventParameter_RBVLV_MV8_VARTFailure              389
#define DemConf_DemEventParameter_RBVLV_MV8_ValveCoilResistanceOutOfRangeFailure  390
#define DemConf_DemEventParameter_RBVLV_MV8_ValveDriverLBISTFailure  391
#define DemConf_DemEventParameter_RBVLV_MV9_ValveCoilPathInterruptionFailure  392
#define DemConf_DemEventParameter_RBVLV_MV9_GeneralValveDriverFailure  393
#define DemConf_DemEventParameter_RBVLV_MV9_ValveDriverGateQxFailure  394
#define DemConf_DemEventParameter_RBVLV_MV9_SVDTFailure              395
#define DemConf_DemEventParameter_RBVLV_MV9_VARTFailure              396
#define DemConf_DemEventParameter_RBVLV_MV9_ValveCoilResistanceOutOfRangeFailure  397
#define DemConf_DemEventParameter_RBVLV_MV9_ValveDriverLBISTFailure  398
#define DemConf_DemEventParameter_RBVLV_GENERIC_SVDTTestNotStoppedFailure  399
#define DemConf_DemEventParameter_RBVLV_GENERIC_UvrLeakageCurrentFailure  400
#define DemConf_DemEventParameter_RBVLV_GENERIC_ValveCoilResistanceMeasurementPathFailure  401
#define DemConf_DemEventParameter_AcmTs_TemperatureUsvOverheat       402
#define DemConf_DemEventParameter_Wss_MonWheelDirGen                 403
#define DemConf_DemEventParameter_Wss_SignFA                         404
#define DemConf_DemEventParameter_Wss_MonGenericTempFail             405
#define DemConf_DemEventParameter_Wss_SignRA                         406
#define DemConf_DemEventParameter_RBWssFLUnderVoltage                407
#define DemConf_DemEventParameter_RBWssRRUnderVoltage                408
#define DemConf_DemEventParameter_RBWssFRUnderVoltage                409
#define DemConf_DemEventParameter_RBWssRLUnderVoltage                410
#define DemConf_DemEventParameter_Dummy04                            411
#define DemConf_DemEventParameter_RBAPBMOTLeftCurrentMeasMon         412
#define DemConf_DemEventParameter_RBAPBMOTRightCurrentMeasMon        413
#define DemConf_DemEventParameter_RBIISSMI7AsFailureIntegral         414
#define DemConf_DemEventParameter_A1A2Range                          415
#define DemConf_DemEventParameter_Scl_E2E_ADataRawSafe_TO            416
#define DemConf_DemEventParameter_Scl_E2E_ADataRawSafe_CHK           417
#define DemConf_DemEventParameter_Scl_E2E_ADataRawSafe_AC            418
#define DemConf_DemEventParameter_Scl_FlexRaySigBrkPedlValQf_InvalidValue  419
#define DemConf_DemEventParameter_ClutchLow                          420
#define DemConf_DemEventParameter_ClutchHigh                         421
#define DemConf_DemEventParameter_ComScl_Msg00_DataCorrupt           422
#define DemConf_DemEventParameter_ComScl_Msg00_Timeout               423
#define DemConf_DemEventParameter_ComScl_Msg01_DataCorrupt           424
#define DemConf_DemEventParameter_ComScl_Msg01_Timeout               425
#define DemConf_DemEventParameter_ComScl_Msg02_DataCorrupt           426
#define DemConf_DemEventParameter_ComScl_Msg02_Timeout               427
#define DemConf_DemEventParameter_ComScl_Msg03_DataCorrupt           428
#define DemConf_DemEventParameter_ComScl_Msg03_Timeout               429
#define DemConf_DemEventParameter_ComScl_Msg09_DataCorrupt           430
#define DemConf_DemEventParameter_ComScl_Msg09_Timeout               431
#define DemConf_DemEventParameter_ComScl_Msg10_DataCorrupt           432
#define DemConf_DemEventParameter_ComScl_Msg10_Timeout               433
#define DemConf_DemEventParameter_ComScl_Msg12_DataCorrupt           434
#define DemConf_DemEventParameter_ComScl_Msg12_Timeout               435
#define DemConf_DemEventParameter_ComScl_Msg13_DataCorrupt           436
#define DemConf_DemEventParameter_ComScl_Msg13_Timeout               437
#define DemConf_DemEventParameter_ComScl_Msg14_DataCorrupt           438
#define DemConf_DemEventParameter_ComScl_Msg14_Timeout               439
#define DemConf_DemEventParameter_ComScl_Msg15_DataCorrupt           440
#define DemConf_DemEventParameter_ComScl_Msg15_Timeout               441
#define DemConf_DemEventParameter_ComScl_Msg18_DataCorrupt           442
#define DemConf_DemEventParameter_ComScl_Msg18_Timeout               443
#define DemConf_DemEventParameter_ComScl_Msg19_DataCorrupt           444
#define DemConf_DemEventParameter_ComScl_Msg19_Timeout               445
#define DemConf_DemEventParameter_ComScl_Msg07_DataCorrupt           446
#define DemConf_DemEventParameter_ComScl_Msg07_Timeout               447
#define DemConf_DemEventParameter_ComScl_Msg04_DataCorrupt           448
#define DemConf_DemEventParameter_ComScl_Msg04_Timeout               449
#define DemConf_DemEventParameter_ComScl_Msg05_DataCorrupt           450
#define DemConf_DemEventParameter_ComScl_Msg05_Timeout               451
#define DemConf_DemEventParameter_ComScl_Msg06_DataCorrupt           452
#define DemConf_DemEventParameter_ComScl_Msg06_Timeout               453
#define DemConf_DemEventParameter_ComScl_Msg08_DataCorrupt           454
#define DemConf_DemEventParameter_ComScl_Msg08_Timeout               455
#define DemConf_DemEventParameter_ComScl_Msg11_DataCorrupt           456
#define DemConf_DemEventParameter_ComScl_Msg11_Timeout               457
#define DemConf_DemEventParameter_ComScl_Msg16_DataCorrupt           458
#define DemConf_DemEventParameter_ComScl_Msg16_Timeout               459
#define DemConf_DemEventParameter_ComScl_Msg17_DataCorrupt           460
#define DemConf_DemEventParameter_ComScl_Msg17_Timeout               461
#define DemConf_DemEventParameter_ReverseGearHigh                    462
#define DemConf_DemEventParameter_ReverseGearLow                     463
#define DemConf_DemEventParameter_Sas_MonMsgCnt                      464
#define DemConf_DemEventParameter_Sas_CondActiveAboveThr             465
#define DemConf_DemEventParameter_Sas_MonOffset                      466
#define DemConf_DemEventParameter_Sas_MonGradSasAdd                  467
#define DemConf_DemEventParameter_Sas_Sign                           468
#define DemConf_DemEventParameter_Sas_MonConstSig                    469
#define DemConf_DemEventParameter_Sas_Plausibility                   470
#define DemConf_DemEventParameter_SasUncertaintyPhase2               471
#define DemConf_DemEventParameter_SasUncertaintyPhase1               472
#define DemConf_DemEventParameter_RBWssFLSupplyGnd                   473
#define DemConf_DemEventParameter_RBWssFLSupplyHigh                  474
#define DemConf_DemEventParameter_RBWssFLLineHigh                    475
#define DemConf_DemEventParameter_RBWssFLLineGnd                     476
#define DemConf_DemEventParameter_RBWssFLLineUndef                   477
#define DemConf_DemEventParameter_RBWssTestFLFailure                 478
#define DemConf_DemEventParameter_RBWssFLAirGap                      479
#define DemConf_DemEventParameter_RBWssFlDmaBufNoise                 480
#define DemConf_DemEventParameter_RBWssFLWrongSens                   481
#define DemConf_DemEventParameter_RBWssFLNoEdge                      482
#define DemConf_DemEventParameter_Wss_MonRange_FL                    483
#define DemConf_DemEventParameter_Wss_MonVDiff_FL                    484
#define DemConf_DemEventParameter_Wss_MonMissingTeeth_FL             485
#define DemConf_DemEventParameter_Wss_MonNoise_FL                    486
#define DemConf_DemEventParameter_Wss_SignalLost_FL                  487
#define DemConf_DemEventParameter_RBWssFRSupplyGnd                   488
#define DemConf_DemEventParameter_RBWssFRSupplyHigh                  489
#define DemConf_DemEventParameter_RBWssFRLineHigh                    490
#define DemConf_DemEventParameter_RBWssFRLineGnd                     491
#define DemConf_DemEventParameter_RBWssFRLineUndef                   492
#define DemConf_DemEventParameter_RBWssTestFRFailure                 493
#define DemConf_DemEventParameter_RBWssFRAirGap                      494
#define DemConf_DemEventParameter_RBWssFrDmaBufNoise                 495
#define DemConf_DemEventParameter_RBWssFRWrongSens                   496
#define DemConf_DemEventParameter_RBWssFRNoEdge                      497
#define DemConf_DemEventParameter_Wss_MonRange_FR                    498
#define DemConf_DemEventParameter_Wss_MonVDiff_FR                    499
#define DemConf_DemEventParameter_Wss_MonMissingTeeth_FR             500
#define DemConf_DemEventParameter_Wss_MonNoise_FR                    501
#define DemConf_DemEventParameter_Wss_SignalLost_FR                  502
#define DemConf_DemEventParameter_RBWssRLSupplyGnd                   503
#define DemConf_DemEventParameter_RBWssRLLineHigh                    504
#define DemConf_DemEventParameter_RBWssRLSupplyHigh                  505
#define DemConf_DemEventParameter_RBWssRLLineGnd                     506
#define DemConf_DemEventParameter_RBWssRLLineUndef                   507
#define DemConf_DemEventParameter_RBWssTestRLFailure                 508
#define DemConf_DemEventParameter_RBWssRLAirGap                      509
#define DemConf_DemEventParameter_RBWssRlDmaBufNoise                 510
#define DemConf_DemEventParameter_RBWssRLWrongSens                   511
#define DemConf_DemEventParameter_RBWssRLNoEdge                      512
#define DemConf_DemEventParameter_Wss_MonRange_RL                    513
#define DemConf_DemEventParameter_Wss_MonVDiff_RL                    514
#define DemConf_DemEventParameter_Wss_MonMissingTeeth_RL             515
#define DemConf_DemEventParameter_Wss_MonNoise_RL                    516
#define DemConf_DemEventParameter_Wss_SignalLost_RL                  517
#define DemConf_DemEventParameter_RBWssRRSupplyGnd                   518
#define DemConf_DemEventParameter_RBWssRRSupplyHigh                  519
#define DemConf_DemEventParameter_RBWssRRLineHigh                    520
#define DemConf_DemEventParameter_RBWssRRLineGnd                     521
#define DemConf_DemEventParameter_RBWssRRLineUndef                   522
#define DemConf_DemEventParameter_RBWssTestRRFailure                 523
#define DemConf_DemEventParameter_RBWssRRAirGap                      524
#define DemConf_DemEventParameter_RBWssRrDmaBufNoise                 525
#define DemConf_DemEventParameter_RBWssRRWrongSens                   526
#define DemConf_DemEventParameter_RBWssRRNoEdge                      527
#define DemConf_DemEventParameter_Wss_MonRange_RR                    528
#define DemConf_DemEventParameter_Wss_MonVDiff_RR                    529
#define DemConf_DemEventParameter_Wss_MonMissingTeeth_RR             530
#define DemConf_DemEventParameter_Wss_MonNoise_RR                    531
#define DemConf_DemEventParameter_Wss_SignalLost_RR                  532
#define DemConf_DemEventParameter_Wss_MoreThanOneSuspected           533
#define DemConf_DemEventParameter_Scl_E2E_AgDataRawSafe_TO           534
#define DemConf_DemEventParameter_Scl_E2E_AgDataRawSafe_CHK          535
#define DemConf_DemEventParameter_Scl_E2E_AgDataRawSafe_AC           536
#define DemConf_DemEventParameter_RBAPBMOTLeftLineMotorRot           537
#define DemConf_DemEventParameter_RBAPBMOTLeftLineOpen               538
#define DemConf_DemEventParameter_RBAPBMOTLeftLineHigh               539
#define DemConf_DemEventParameter_RBAPBMOTLeftLineGnd                540
#define DemConf_DemEventParameter_RBAPBMOTLeftOther                  541
#define DemConf_DemEventParameter_RBAPBMOTLeftUnspecificCoupling     542
#define DemConf_DemEventParameter_RBAPBMOTLeftHBridgeCMCT            543
#define DemConf_DemEventParameter_RBAPBMOTLeftHBridgeCMST            544
#define DemConf_DemEventParameter_RBAPBMOTLeftHBridgeCMET            545
#define DemConf_DemEventParameter_RBAPBMOTRightLineMotorRot          546
#define DemConf_DemEventParameter_RBAPBMOTRightLineOpen              547
#define DemConf_DemEventParameter_RBAPBMOTRightLineHigh              548
#define DemConf_DemEventParameter_RBAPBMOTRightLineGnd               549
#define DemConf_DemEventParameter_RBAPBMOTRightOther                 550
#define DemConf_DemEventParameter_RBAPBMOTRightUnspecificCoupling    551
#define DemConf_DemEventParameter_RBAPBMOTRightHBridgeCMCT           552
#define DemConf_DemEventParameter_RBAPBMOTRightHBridgeCMST           553
#define DemConf_DemEventParameter_RBAPBMOTRightHBridgeCMET           554
#define DemConf_DemEventParameter_Axs_MonRange                       555
#define DemConf_DemEventParameter_Axs_MonConstSig                    556
#define DemConf_DemEventParameter_AxsOffset                          557
#define DemConf_DemEventParameter_Axs_MonPlaus                       558
#define DemConf_DemEventParameter_AxsUncertaintyPhase1               559
#define DemConf_DemEventParameter_AxsUncertaintyPhase2               560
#define DemConf_DemEventParameter_Ays_MonRedundancy                  561
#define DemConf_DemEventParameter_AysOffset                          562
#define DemConf_DemEventParameter_Ays_MonRange                       563
#define DemConf_DemEventParameter_AysPlaus                           564
#define DemConf_DemEventParameter_AysUncertaintyPhase1               565
#define DemConf_DemEventParameter_AysUncertaintyPhase2               566
#define DemConf_DemEventParameter_AcmPbs_PlausPsBlsTh1               567
#define DemConf_DemEventParameter_AcmPbs_PlausPsBlsTh3               568
#define DemConf_DemEventParameter_AcmBls_PermHigh                    569
#define DemConf_DemEventParameter_Dummy03                            570
#define DemConf_DemEventParameter_Wss_MonWheelDir_FL                 571
#define DemConf_DemEventParameter_Wss_MonWheelDir_FR                 572
#define DemConf_DemEventParameter_Wss_MonWheelDir_RL                 573
#define DemConf_DemEventParameter_Wss_MonWheelDir_RR                 574
#define DemConf_DemEventParameter_RBIISSMI7YrsFailureIntegral        575
#define DemConf_DemEventParameter_Yrs_MonBite                        576
#define DemConf_DemEventParameter_Yrs_MonMsgCnt                      577
#define DemConf_DemEventParameter_Yrs2_MonOffset                     578
#define DemConf_DemEventParameter_Yrs2_FaultAssignment               579
#define DemConf_DemEventParameter_Yrs1_FaultAssignment               580
#define DemConf_DemEventParameter_Yrs_MonRedundancy                  581
#define DemConf_DemEventParameter_Yrs_Sign                           582
#define DemConf_DemEventParameter_YrsPlaus                           583
#define DemConf_DemEventParameter_TarYawExtUncertaintyPhase1         584
#define DemConf_DemEventParameter_TarYawExtUncertaintyPhase2         585
#define DemConf_DemEventParameter_YrsUncertaintyPhase1               586
#define DemConf_DemEventParameter_YrsUncertaintyPhase2               587
#define DemConf_DemEventParameter_RBAPBMOTOverCurrentLeft            588
#define DemConf_DemEventParameter_RBAPBMOTGateMonLeft                589
#define DemConf_DemEventParameter_RBAPBMOTDrainSourceMonLeft         590
#define DemConf_DemEventParameter_RBAPBMOTOverCurrentRight           591
#define DemConf_DemEventParameter_RBAPBMOTGateMonRight               592
#define DemConf_DemEventParameter_RBAPBMOTDrainSourceMonRight        593
#define DemConf_DemEventParameter_RBAPBMOTSupplyUndervoltage         594
#define DemConf_DemEventParameter_RBAPBMOTSupplyOvervoltage          595
#define DemConf_DemEventParameter_AcmBls_PermHighHHC                 596
#define DemConf_DemEventParameter_MoCMonLMotorPolarity               597
#define DemConf_DemEventParameter_MoCMonLMotStallDurRel              598
#define DemConf_DemEventParameter_MoCMonRMotorPolarity               599
#define DemConf_DemEventParameter_MoCMonRMotStallDurRel              600
#define DemConf_DemEventParameter_MoCMonLMotStallDurLock             601
#define DemConf_DemEventParameter_MoCMonRMotStallDurLock             602





#endif

